--[[

	Atlas, a World of Warcraft instance map browser
	Copyright 2005 - 2008 Dan Gilbert
	Email me at loglow@gmail.com

	This file is part of Atlas.

	Atlas is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2 of the License, or
	(at your option) any later version.

	Atlas is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with Atlas; if not, write to the Free Software
	Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

--]]

--[[

-- Atlas Data
-- Compiled by Dan Gilbert
-- loglow@gmail.com
-- Many thanks to all contributors!
-- Now with GUIDs!
-- Now externally localized!

--]]

local BLUE = "|cff6666ff";
local GREY = "|cff999999";
local GREN = "|cff66cc33";
local _RED = "|cffcc6666";
local ORNG = "|cffcc9933";
local PURP = "|cff9900ff";
local INDENT = "      ";

local ZONE = 1;
local NPC = 2;
local ITEM = 3;
local OBJECT = 4;
local FACTION = 5;
local QUEST = 6;

AtlasMaps = {

--************************************************
-- Kalimdor Instances
--************************************************

	RagefireChasm = {
		ZoneName = { AtlasLocale["Ragefire Chasm"], 2437 };
		Acronym = AtlasLocale["RFC"];
		Location = { AtlasLocale["Orgrimmar"], 1637 };
		LevelRange = "12-18";
		PlayerLimit = "10";
		Continent = AtlasLocale["Kalimdor"];
		{ BLUE.."A) "..AtlasLocale["Entrance"] };
		{ GREY.."1) "..AtlasLocale["Maur Grimtotem"], NPC, 11834 };
		{ GREY..INDENT..AtlasLocale["Oggleflint <Ragefire Chieftain>"], NPC, 11517 };
		{ GREY.."2) "..AtlasLocale["Taragaman the Hungerer"], NPC, 11520 };
		{ GREY.."3) "..AtlasLocale["Jergosh the Invoker"], NPC, 11518 };
		{ GREY..INDENT..AtlasLocale["Zelemar the Wrathful"].." ("..AtlasLocale["Summon"]..")", NPC, 17830 };
		{ GREY.."4) "..AtlasLocale["Bazzalan"], NPC, 11519 };
	};
	WailingCaverns = {
		ZoneName = { AtlasLocale["Wailing Caverns"], 718 };
		Acronym = AtlasLocale["WC"];
		Location = { AtlasLocale["The Barrens"], 17 };
		LevelRange = "16-25";
		PlayerLimit = "10";
		Continent = AtlasLocale["Kalimdor"];
		{ BLUE.."A) "..AtlasLocale["Entrance"] };
		{ GREY.."1) "..AtlasLocale["Disciple of Naralex"], NPC, 3678 };
		{ GREY.."2) "..AtlasLocale["Lord Cobrahn <Fanglord>"], NPC, 3669 };
		{ GREY.."3) "..AtlasLocale["Lady Anacondra <Fanglord>"], NPC, 3671 };
		{ GREY.."4) "..AtlasLocale["Kresh"], NPC, 3653 };
		{ GREY.."5) "..AtlasLocale["Lord Pythas <Fanglord>"], NPC, 3670 };
		{ GREY.."6) "..AtlasLocale["Skum"], NPC, 3674 };
		{ GREY.."7) "..AtlasLocale["Lord Serpentis <Fanglord>"].." ("..AtlasLocale["Upper"]..")", NPC, 3673 };
		{ GREY.."8) "..AtlasLocale["Verdan the Everliving"].." ("..AtlasLocale["Upper"]..")", NPC, 5775 };
		{ GREY.."9) "..AtlasLocale["Mutanus the Devourer"], NPC, 3654 };
		{ GREY..INDENT..AtlasLocale["Naralex"], NPC, 3679 };
		{ GREY.."10) "..AtlasLocale["Deviate Faerie Dragon"].." ("..AtlasLocale["Rare"]..")", NPC, 5912 };
	};
	BlackfathomDeeps = {
		ZoneName = { AtlasLocale["Blackfathom Deeps"], 719 };
		Acronym = AtlasLocale["BFD"];
		Location = { AtlasLocale["Ashenvale"], 331 };
		LevelRange = "20-28";
		PlayerLimit = "10";
		Continent = AtlasLocale["Kalimdor"];
		{ BLUE.."A) "..AtlasLocale["Entrance"] };
		{ GREY.."1) "..AtlasLocale["Ghamoo-ra"], NPC, 4887 };
		{ GREY.."2) "..AtlasLocale["Lorgalis Manuscript"], ITEM, 5359 };
		{ GREY.."3) "..AtlasLocale["Lady Sarevess"], NPC, 4831 };
		{ GREY.."4) "..AtlasLocale["Argent Guard Thaelrid <The Argent Dawn>"], NPC, 4787 };
		{ GREY.."5) "..AtlasLocale["Gelihast"], NPC, 6243 };
		{ GREY..INDENT..AtlasLocale["Shrine of Gelihast"] };
		{ GREY.."6) "..AtlasLocale["Lorgus Jett"].." ("..AtlasLocale["Varies"]..")", NPC, 12902 };
		{ GREY.."7) "..AtlasLocale["Fathom Stone"], OBJECT, 177964 };
		{ GREY..INDENT..AtlasLocale["Baron Aquanis"], NPC, 12876 };
		{ GREY.."8) "..AtlasLocale["Twilight Lord Kelris"], NPC, 4832 };
		{ GREY.."9) "..AtlasLocale["Old Serra'kis"], NPC, 4830 };
		{ GREY.."10) "..AtlasLocale["Aku'mai"], NPC, 4829 };
		{ GREY..INDENT..AtlasLocale["Morridune"], NPC, 6729 };
		{ GREY..INDENT..AtlasLocale["Altar of the Deeps"] };
	};
	RazorfenKraul = {
		ZoneName = { AtlasLocale["Razorfen Kraul"], 491 };
		Acronym = AtlasLocale["RFK"];
		Location = { AtlasLocale["The Barrens"], 17 };
		LevelRange = "23-33";
		PlayerLimit = "10";
		Continent = AtlasLocale["Kalimdor"];
		{ BLUE.."A) "..AtlasLocale["Entrance"] };
		{ GREY.."1) "..AtlasLocale["Roogug"], NPC, 6168 };
		{ GREY.."2) "..AtlasLocale["Aggem Thorncurse <Death's Head Prophet>"], NPC, 4424 };
		{ GREY.."3) "..AtlasLocale["Death Speaker Jargba <Death's Head Captain>"], NPC, 4428 };
		{ GREY.."4) "..AtlasLocale["Overlord Ramtusk"], NPC, 4420 };
		{ GREY..INDENT..AtlasLocale["Razorfen Spearhide"], NPC, 4438 };
		{ GREY.."5) "..AtlasLocale["Agathelos the Raging"], NPC, 4422 };
		{ GREY.."6) "..AtlasLocale["Blind Hunter"].." ("..AtlasLocale["Rare"]..")", NPC, 4425 };
		{ GREY.."7) "..AtlasLocale["Charlga Razorflank <The Crone>"], NPC, 4421 };
		{ GREY.."8) "..AtlasLocale["Willix the Importer"], NPC, 4508 };
		{ GREY..INDENT..AtlasLocale["Heralath Fallowbrook"], NPC, 4510 };
		{ GREY.."9) "..AtlasLocale["Earthcaller Halmgar"].." ("..AtlasLocale["Rare"]..")", NPC, 4842 };
	};
	RazorfenDowns = {
		ZoneName = { AtlasLocale["Razorfen Downs"], 722 };
		Acronym = AtlasLocale["RFD"];
		Location = { AtlasLocale["The Barrens"], 17 };
		LevelRange = "33-42";
		PlayerLimit = "10";
		Continent = AtlasLocale["Kalimdor"];
		{ BLUE.."A) "..AtlasLocale["Entrance"] };
		{ GREY.."1) "..AtlasLocale["Tuten'kash"], NPC, 7355 };
		{ GREY.."2) "..AtlasLocale["Henry Stern"], NPC, 8696 };
		{ GREY..INDENT..AtlasLocale["Belnistrasz"], NPC, 8516 };
		{ GREY..INDENT..AtlasLocale["Sah'rhee"], NPC, 8767 };
		{ GREY.."3) "..AtlasLocale["Mordresh Fire Eye"], NPC, 7357 };
		{ GREY.."4) "..AtlasLocale["Glutton"], NPC, 8567 };
		{ GREY.."5) "..AtlasLocale["Ragglesnout"].." ("..AtlasLocale["Rare"]..", "..AtlasLocale["Varies"]..")", NPC, 7354 };
		{ GREY.."6) "..AtlasLocale["Amnennar the Coldbringer"], NPC, 7358 };
		{ GREY.."7) "..AtlasLocale["Plaguemaw the Rotting"], NPC, 7356 };
	};
	ZulFarrak = {
		ZoneName = { AtlasLocale["Zul'Farrak"], 978 };
		Acronym = AtlasLocale["ZF"];
		Location = { AtlasLocale["Tanaris"], 440 };
		LevelRange = "42-48";
		PlayerLimit = "10";
		Continent = AtlasLocale["Kalimdor"];
		{ ORNG..AtlasLocale["Key"]..": "..AtlasLocale["Mallet of Zul'Farrak"].." ("..AtlasLocale["Gahz'rilla"]..")", ITEM, 9240 };
		{ BLUE.."A) "..AtlasLocale["Entrance"] };
		{ GREY.."1) "..AtlasLocale["Antu'sul <Overseer of Sul>"], NPC, 8127 };
		{ GREY.."2) "..AtlasLocale["Theka the Martyr"], NPC, 7272 };
		{ GREY.."3) "..AtlasLocale["Witch Doctor Zum'rah"], NPC, 7271 };
		{ GREY..INDENT..AtlasLocale["Zul'Farrak Dead Hero"], NPC, 7276 };
		{ GREY.."4) "..AtlasLocale["Nekrum Gutchewer"], NPC, 7796 };
		{ GREY..INDENT..AtlasLocale["Shadowpriest Sezz'ziz"], NPC, 7275 };
		{ GREY..INDENT..AtlasLocale["Dustwraith"].." ("..AtlasLocale["Rare"]..")", NPC, 10081 };
		{ GREY.."5) "..AtlasLocale["Sergeant Bly"], NPC, 7604 };
		{ GREY..INDENT..AtlasLocale["Weegli Blastfuse"], NPC, 7607 };
		{ GREY..INDENT..AtlasLocale["Murta Grimgut"], NPC, 7608 };
		{ GREY..INDENT..AtlasLocale["Raven"], NPC, 7605 };
		{ GREY..INDENT..AtlasLocale["Oro Eyegouge"], NPC, 7606 };
		{ GREY..INDENT..AtlasLocale["Sandfury Executioner"], NPC, 7274 };
		{ GREY.."6) "..AtlasLocale["Hydromancer Velratha"], NPC, 7795 };
		{ GREY..INDENT..AtlasLocale["Gahz'rilla"].." ("..AtlasLocale["Summon"]..")", NPC, 7273 };
		{ GREY..INDENT..AtlasLocale["Elder Wildmane"].." ("..AtlasLocale["Lunar"]..")", NPC, 15578 };
		{ GREY.."7) "..AtlasLocale["Chief Ukorz Sandscalp"], NPC, 7267 };
		{ GREY..INDENT..AtlasLocale["Ruuzlu"], NPC, 7797 };
		{ GREY.."8) "..AtlasLocale["Zerillis"].." ("..AtlasLocale["Rare"]..", "..AtlasLocale["Wanders"]..")", NPC, 10082 };
		{ GREY.."9) "..AtlasLocale["Sandarr Dunereaver"].." ("..AtlasLocale["Rare"]..")", NPC, 10080 };
	};
	Maraudon = {
		ZoneName = { AtlasLocale["Maraudon"], 2100 };
		Acronym = AtlasLocale["Mara"];
		Location = { AtlasLocale["Desolace"], 405 };
		LevelRange = "42-51";
		PlayerLimit = "10";
		Continent = AtlasLocale["Kalimdor"];
		{ ORNG..AtlasLocale["Key"]..": "..AtlasLocale["Scepter of Celebras"].." ("..AtlasLocale["Portal"]..")", ITEM, 17191 };
		{ BLUE.."A) "..AtlasLocale["Entrance"].." ("..AtlasLocale["Orange"]..")" };
		{ BLUE.."B) "..AtlasLocale["Entrance"].." ("..AtlasLocale["Purple"]..")" };
		{ BLUE.."C) "..AtlasLocale["Entrance"].." ("..AtlasLocale["Portal"]..")" };
		{ GREY.."1) "..AtlasLocale["Veng <The Fifth Khan>"], NPC, 13738 };
		{ GREY.."2) "..AtlasLocale["Noxxion"], NPC, 13282 };
		{ GREY.."3) "..AtlasLocale["Razorlash"], NPC, 12258 };
		{ GREY.."4) "..AtlasLocale["Maraudos <The Fourth Khan>"], NPC, 13739 };
		{ GREY.."5) "..AtlasLocale["Lord Vyletongue"], NPC, 12236 };
		{ GREY.."6) "..AtlasLocale["Meshlok the Harvester"].." ("..AtlasLocale["Rare"]..")", NPC, 12237 };
		{ GREY.."7) "..AtlasLocale["Celebras the Cursed"], NPC, 12225 };
		{ GREY.."8) "..AtlasLocale["Landslide"], NPC, 12203 };
		{ GREY.."9) "..AtlasLocale["Tinkerer Gizlock"], NPC, 13601 };
		{ GREY.."10) "..AtlasLocale["Rotgrip"], NPC, 13596 };
		{ GREY.."11) "..AtlasLocale["Princess Theradras"], NPC, 12201 };
		{ GREY.."12) "..AtlasLocale["Elder Splitrock"].." ("..AtlasLocale["Lunar"]..")", NPC, 15556 };
	};
	DireMaulEast = {
		ZoneName = { AtlasLocale["Dire Maul (East)"], 2557 };
		Acronym = AtlasLocale["DM"];
		Location = { AtlasLocale["Feralas"], 357 };
		LevelRange = "55-58";
		PlayerLimit = "5";
		Continent = AtlasLocale["Kalimdor"];
		{ ORNG..AtlasLocale["Key"]..": "..AtlasLocale["Brazier of Invocation"].." ("..AtlasLocale["DS2"]..")", ITEM, 22057 };
		{ BLUE.."A) "..AtlasLocale["Entrance"] };
		{ BLUE.."B) "..AtlasLocale["Entrance"] };
		{ BLUE.."C) "..AtlasLocale["Entrance"] };
		{ BLUE.."D) "..AtlasLocale["Exit"] };
		{ GREY.."1) "..AtlasLocale["Pusillin"].." ("..AtlasLocale["Chase Begins"]..")", NPC, 14354 };
		{ GREY.."2) "..AtlasLocale["Pusillin"].." ("..AtlasLocale["Chase Ends"]..")", NPC, 14354 };
		{ GREY.."3) "..AtlasLocale["Zevrim Thornhoof"], NPC, 11490 };
		{ GREY..INDENT..AtlasLocale["Hydrospawn"], NPC, 13280 };
		{ GREY..INDENT..AtlasLocale["Lethtendris"], NPC, 14327 };
		{ GREY..INDENT..AtlasLocale["Pimgib"], NPC, 14349 };
		{ GREY.."4) "..AtlasLocale["Old Ironbark"], NPC, 11491 };
		{ GREY.."5) "..AtlasLocale["Alzzin the Wildshaper"], NPC, 11492 };
		{ GREY..INDENT..AtlasLocale["Isalien"].." ("..AtlasLocale["Summon"]..")", NPC, 16097 };
	};
	DireMaulNorth = {
		ZoneName = { AtlasLocale["Dire Maul (North)"], 2557 };
		Acronym = AtlasLocale["DM"];
		Location = { AtlasLocale["Feralas"], 357 };
		LevelRange = "57-60";
		PlayerLimit = "5";
		Continent = AtlasLocale["Kalimdor"];
		{ ORNG..AtlasLocale["Key"]..": "..AtlasLocale["Crescent Key"], ITEM, 18249 };
		{ BLUE.."A) "..AtlasLocale["Entrance"] };
		{ BLUE.."B) "..AtlasLocale["Library"] };
		{ GREY.."1) "..AtlasLocale["Guard Mol'dar"], NPC, 14326 };
		{ GREY.."2) "..AtlasLocale["Stomper Kreeg <The Drunk>"], NPC, 14322 };
		{ GREY.."3) "..AtlasLocale["Guard Fengus"], NPC, 14321 };
		{ GREY.."4) "..AtlasLocale["Knot Thimblejack"], NPC, 14338 };
		{ GREY..INDENT..AtlasLocale["Guard Slip'kik"], NPC, 14323 };
		{ GREY.."5) "..AtlasLocale["Captain Kromcrush"], NPC, 14325 };
		{ GREY.."6) "..AtlasLocale["King Gordok"], NPC, 11501 };
		{ GREY..INDENT..AtlasLocale["Cho'Rush the Observer"], NPC, 14324 };
	};
	DireMaulWest = {
		ZoneName = { AtlasLocale["Dire Maul (West)"], 2557 };
		Acronym = AtlasLocale["DM"];
		Location = { AtlasLocale["Feralas"], 357 };
		LevelRange = "57-60";
		PlayerLimit = "5";
		Continent = AtlasLocale["Kalimdor"];
		{ ORNG..AtlasLocale["Key"]..": "..AtlasLocale["Crescent Key"], ITEM, 18249 };
		{ ORNG..AtlasLocale["Key"]..": "..AtlasLocale["J'eevee's Jar"].." ("..AtlasLocale["Lord Hel'nurath"]..")", ITEM, 18663 };
		{ BLUE.."A) "..AtlasLocale["Entrance"] };
		{ BLUE.."B) "..AtlasLocale["Pylons"] };
		{ GREY.."1) "..AtlasLocale["Shen'dralar Ancient"], NPC, 14358 };
		{ GREY.."2) "..AtlasLocale["Tendris Warpwood"], NPC, 11489 };
		{ GREY..INDENT..AtlasLocale["Ancient Equine Spirit"], NPC, 14566 };
		{ GREY.."3) "..AtlasLocale["Illyanna Ravenoak"], NPC, 11488 };
		{ GREY..INDENT..AtlasLocale["Ferra"], NPC, 14308 };
		{ GREY.."4) "..AtlasLocale["Magister Kalendris"], NPC, 11487 };
		{ GREY.."5) "..AtlasLocale["Tsu'zee"].." ("..AtlasLocale["Rare"]..")", NPC, 11467 };
		{ GREY.."6) "..AtlasLocale["Immol'thar"], NPC, 11496 };
		{ GREY..INDENT..AtlasLocale["Lord Hel'nurath"].." ("..AtlasLocale["Summon"]..")", NPC, 14506 };
		{ GREY.."7) "..AtlasLocale["Prince Tortheldrin"], NPC, 11486 };
		{ GREN.."1') "..AtlasLocale["Library"] };
		{ GREN..INDENT..AtlasLocale["Falrin Treeshaper"], NPC, 16032 };
		{ GREN..INDENT..AtlasLocale["Lorekeeper Lydros"], NPC, 14368 };
		{ GREN..INDENT..AtlasLocale["Lorekeeper Javon"], NPC, 14381 };
		{ GREN..INDENT..AtlasLocale["Lorekeeper Kildrath"], NPC, 14383 };
		{ GREN..INDENT..AtlasLocale["Lorekeeper Mykos"], NPC, 14382 };
		{ GREN..INDENT..AtlasLocale["Shen'dralar Provisioner"], NPC, 14371 };
		{ GREN..INDENT..AtlasLocale["Skeletal Remains of Kariel Winthalus"], OBJECT, 179544 };
	};
	OnyxiasLair = {
		ZoneName = { AtlasLocale["Onyxia's Lair"], 2159 };
		Acronym = AtlasLocale["Ony"];
		Location = { AtlasLocale["Dustwallow Marsh"], 15 };
		LevelRange = "60-70";
		PlayerLimit = "40";
		Continent = AtlasLocale["Kalimdor"];
		{ ORNG..AtlasLocale["Attunement Required"] };
		{ ORNG..AtlasLocale["Key"]..": "..AtlasLocale["Drakefire Amulet"], ITEM, 16309 };
		{ BLUE.."A) "..AtlasLocale["Entrance"] };
		{ GREY.."1) "..AtlasLocale["Onyxian Warders"], NPC, 12129 };
		{ GREY.."2) "..AtlasLocale["Whelp Eggs"] };
		{ GREY.."3) "..AtlasLocale["Onyxia"], NPC, 10184 };
	};
	TheTempleofAhnQiraj = {
		ZoneName = { AtlasLocale["Temple of Ahn'Qiraj"], 3428 };
		Acronym = AtlasLocale["AQ40"];
		Location = { AtlasLocale["Silithus"], 1377 };
		LevelRange = "60-70";
		PlayerLimit = "40";
		Continent = AtlasLocale["Kalimdor"];
		{ ORNG..AtlasLocale["Rep"]..": "..AtlasLocale["Brood of Nozdormu"], FACTION, 910 };
		{ BLUE.."A) "..AtlasLocale["Entrance"] };
		{ GREY.."1) "..AtlasLocale["The Prophet Skeram"].." ("..AtlasLocale["Outside"]..")", NPC, 15263 };
		{ GREY.."2) "..AtlasLocale["The Bug Family"].." ("..AtlasLocale["Optional"]..")" };
		{ GREY..INDENT..AtlasLocale["Vem"], NPC, 15544 };
		{ GREY..INDENT..AtlasLocale["Lord Kri"], NPC, 15511 };
		{ GREY..INDENT..AtlasLocale["Princess Yauj"], NPC, 15543 };
		{ GREY.."3) "..AtlasLocale["Battleguard Sartura"], NPC, 15516 };
		{ GREY.."4) "..AtlasLocale["Fankriss the Unyielding"], NPC, 15510 };
		{ GREY.."5) "..AtlasLocale["Viscidus"].." ("..AtlasLocale["Optional"]..")", NPC, 15299 };
		{ GREY.."6) "..AtlasLocale["Princess Huhuran"], NPC, 15509 };
		{ GREY.."7) "..AtlasLocale["Twin Emperors"] };
		{ GREY..INDENT..AtlasLocale["Emperor Vek'lor"], NPC, 15276 };
		{ GREY..INDENT..AtlasLocale["Emperor Vek'nilash"], NPC, 15275 };
		{ GREY.."8) "..AtlasLocale["Ouro"].." ("..AtlasLocale["Optional"]..")", NPC, 15517 };
		{ GREY.."9) "..AtlasLocale["Eye of C'Thun"], NPC, 15589 };
		{ GREY..INDENT..AtlasLocale["C'Thun"], NPC, 15727 };
		{ GREN.."1') "..AtlasLocale["Andorgos <Brood of Malygos>"], NPC, 15502 };
		{ GREN..INDENT..AtlasLocale["Vethsera <Brood of Ysera>"], NPC, 15504 };
		{ GREN..INDENT..AtlasLocale["Kandrostrasz <Brood of Alexstrasza>"], NPC, 15503 };
		{ GREN.."2') "..AtlasLocale["Arygos"], NPC, 15380 };
		{ GREN..INDENT..AtlasLocale["Caelestrasz"], NPC, 15379 };
		{ GREN..INDENT..AtlasLocale["Merithra of the Dream"], NPC, 15378 };
	};
	TheRuinsofAhnQiraj = {
		ZoneName = { AtlasLocale["Ruins of Ahn'Qiraj"], 3429 };
		Acronym = AtlasLocale["AQ20"];
		Location = { AtlasLocale["Silithus"], 1377 };
		LevelRange = "60-70";
		PlayerLimit = "20";
		Continent = AtlasLocale["Kalimdor"];
		{ ORNG..AtlasLocale["Rep"]..": "..AtlasLocale["Cenarion Circle"], FACTION, 609 };
		{ BLUE.."A) "..AtlasLocale["Entrance"] };
		{ GREY.."1) "..AtlasLocale["Kurinnaxx"], NPC, 15348 };
		{ GREY..INDENT..AtlasLocale["Lieutenant General Andorov"], NPC, 15471 };
		{ GREY..INDENT..AtlasLocale["Four Kaldorei Elites"], NPC, 15473 };
		{ GREY.."2) "..AtlasLocale["General Rajaxx"], NPC, 15341 };
		{ GREY..INDENT..AtlasLocale["Captain Qeez"], NPC, 15391 };
		{ GREY..INDENT..AtlasLocale["Captain Tuubid"], NPC, 15392 };
		{ GREY..INDENT..AtlasLocale["Captain Drenn"], NPC, 15389 };
		{ GREY..INDENT..AtlasLocale["Captain Xurrem"], NPC, 15390 };
		{ GREY..INDENT..AtlasLocale["Major Yeggeth"], NPC, 15386 };
		{ GREY..INDENT..AtlasLocale["Major Pakkon"], NPC, 15388 };
		{ GREY..INDENT..AtlasLocale["Colonel Zerran"], NPC, 15385 };
		{ GREY.."3) "..AtlasLocale["Moam"].." ("..AtlasLocale["Optional"]..")", NPC, 15340 };
		{ GREY.."4) "..AtlasLocale["Buru the Gorger"].." ("..AtlasLocale["Optional"]..")", NPC, 15370 };
		{ GREY.."5) "..AtlasLocale["Ayamiss the Hunter"].." ("..AtlasLocale["Optional"]..")", NPC, 15369 };
		{ GREY.."6) "..AtlasLocale["Ossirian the Unscarred"], NPC, 15339 };
		{ GREN.."1') "..AtlasLocale["Safe Room"] };
	};
	CoTBlackMorass = {
		ZoneName = { AtlasLocale["CoT: The Black Morass"], 2366 };
		Acronym = AtlasLocale["CoT2"];
		Location = { AtlasLocale["Caverns of Time, Tanaris"], 440 };
		LevelRange = "68-70";
		PlayerLimit = "5";
		Continent = AtlasLocale["Kalimdor"];
		{ PURP..AtlasLocale["Event"]..": "..AtlasLocale["Opening of the Dark Portal"] };
		{ ORNG..AtlasLocale["Attunement Required"] };
		{ ORNG..AtlasLocale["Rep"]..": "..AtlasLocale["Keepers of Time"], FACTION, 989 };
		{ ORNG..AtlasLocale["Key"]..": "..AtlasLocale["Key of Time"].." ("..AtlasLocale["Heroic"]..")", ITEM, 30635 };
		{ BLUE.."A) "..AtlasLocale["Entrance"] };
		{ BLUE..INDENT..AtlasLocale["Sa'at <Keepers of Time>"], NPC, 20201 };
		{ ORNG.."X) "..AtlasLocale["Portal"].." ("..AtlasLocale["Spawn Point"]..")" };
		{ ORNG..INDENT..AtlasLocale["Wave 6: Chrono Lord Deja"], NPC, 17879 };
		{ ORNG..INDENT..AtlasLocale["Wave 12: Temporus"], NPC, 17880 };
		{ ORNG..INDENT..AtlasLocale["Wave 18: Aeonus"], NPC, 17881 };
		{ GREY.."1) "..AtlasLocale["The Dark Portal"] };
		{ GREY..INDENT..AtlasLocale["Medivh"], NPC, 15608 };
	};
	CoTHyjal = {
		ZoneName = { AtlasLocale["CoT: Hyjal Summit"], 3606 };
		Acronym = AtlasLocale["CoT3"];
		Location = { AtlasLocale["Caverns of Time, Tanaris"], 440 };
		LevelRange = "70";
		PlayerLimit = "25";
		Continent = AtlasLocale["Kalimdor"];
		{ PURP..AtlasLocale["Event"]..": "..AtlasLocale["Battle for Mount Hyjal"] };
		{ ORNG..AtlasLocale["Rep"]..": "..AtlasLocale["The Scale of the Sands"], FACTION, 990 };
		{ BLUE.."A) "..AtlasLocale["Alliance Base"] };
		{ BLUE..INDENT..AtlasLocale["Lady Jaina Proudmoore"], NPC, 17772 };
		{ BLUE.."B) "..AtlasLocale["Horde Encampment"] };
		{ BLUE..INDENT..AtlasLocale["Thrall <Warchief>"], NPC, 17852 };
		{ BLUE.."C) "..AtlasLocale["Night Elf Village"] };
		{ BLUE..INDENT..AtlasLocale["Tyrande Whisperwind <High Priestess of Elune>"], NPC, 7999 };
		{ GREY.."1) "..AtlasLocale["Rage Winterchill"], NPC, 17767 };
		{ GREY.."2) "..AtlasLocale["Anetheron"], NPC, 17808 };
		{ GREY.."3) "..AtlasLocale["Kaz'rogal"], NPC, 17888 };
		{ GREY.."4) "..AtlasLocale["Azgalor"], NPC, 17842 };
		{ GREY.."5) "..AtlasLocale["Archimonde"], NPC, 17968 };
		{ GREY.."?) "..AtlasLocale["Indormi <Keeper of Ancient Gem Lore>"], NPC, 23437 };
		{ GREY..INDENT..AtlasLocale["Tydormu <Keeper of Lost Artifacts>"], NPC, 23381 };
	};
	CoTOldHillsbrad = {
		ZoneName = { AtlasLocale["CoT: Old Hillsbrad Foothills"], 2367 };
		Acronym = AtlasLocale["CoT1"];
		Location = { AtlasLocale["Caverns of Time, Tanaris"], 440 };
		LevelRange = "66-70";
		PlayerLimit = "5";
		Continent = AtlasLocale["Kalimdor"];
		{ PURP..AtlasLocale["Event"]..": "..AtlasLocale["Escape from Durnholde Keep"] };
		{ ORNG..AtlasLocale["Attunement Required"] };
		{ ORNG..AtlasLocale["Rep"]..": "..AtlasLocale["Keepers of Time"], FACTION, 989 };
		{ ORNG..AtlasLocale["Key"]..": "..AtlasLocale["Key of Time"].." ("..AtlasLocale["Heroic"]..")", ITEM, 30635 };
		{ BLUE.."A) "..AtlasLocale["Entrance"] };
		{ BLUE..INDENT..AtlasLocale["Erozion"], NPC, 18723 };
		{ BLUE..INDENT..AtlasLocale["Brazen"], NPC, 18725 };
		{ BLUE.."B) "..AtlasLocale["Landing Spot"] };
		{ BLUE.."C) "..AtlasLocale["Southshore"] };
		{ BLUE.."D) "..AtlasLocale["Tarren Mill"] };
		{ GREY.."1) "..AtlasLocale["Lieutenant Drake"], NPC, 17848 };
		{ GREY.."2) "..AtlasLocale["Thrall"].." ("..AtlasLocale["Lower"]..")", NPC, 17876 };
		{ GREY.."3) "..AtlasLocale["Captain Skarloc"], NPC, 17862 };
		{ GREY..INDENT..AtlasLocale["Thrall"].." ("..AtlasLocale["Second Stop"]..")", NPC, 17876 };
		{ GREY.."4) "..AtlasLocale["Thrall"].." ("..AtlasLocale["Third Stop"]..")", NPC, 17876 };
		{ GREY.."5) "..AtlasLocale["Epoch Hunter"], NPC, 18096 };
		{ GREY..INDENT..AtlasLocale["Thrall"].." ("..AtlasLocale["Fourth Stop"]..", "..AtlasLocale["Upstairs"]..")", NPC, 17876 };
		{ GREY..INDENT..AtlasLocale["Taretha"].." ("..AtlasLocale["Upstairs"]..")", NPC, 18887 };
		{ GREY.."6) "..AtlasLocale["Jonathan Revah"], NPC, 20372 };
		{ GREY..INDENT..AtlasLocale["Jerry Carter"], NPC, 20376 };
		{ "" };
		{ ORNG..AtlasLocale["Traveling"] };
		{ GREY..INDENT..AtlasLocale["Thomas Yance <Travelling Salesman>"], NPC, 18672 };
		{ GREY..INDENT..AtlasLocale["Aged Dalaran Wizard"], NPC, 18664 };
		{ "" };
		{ ORNG..AtlasLocale["Southshore"] };
		{ GREY..INDENT..AtlasLocale["Kel'Thuzad <The Kirin Tor>"], NPC, 20350 };
		{ GREY..INDENT..AtlasLocale["Helcular"], NPC, 20353 };
		{ GREY..INDENT..AtlasLocale["Farmer Kent"], NPC, 20368 };
		{ GREY..INDENT..AtlasLocale["Sally Whitemane"], NPC, 20357 };
		{ GREY..INDENT..AtlasLocale["Renault Mograine"], NPC, 20358 };
		{ GREY..INDENT..AtlasLocale["Little Jimmy Vishas"], NPC, 20359 };
		{ GREY..INDENT..AtlasLocale["Herod the Bully"], NPC, 20360 };
		{ GREY..INDENT..AtlasLocale["Nat Pagle"], NPC, 20344 };
		{ GREY..INDENT..AtlasLocale["Hal McAllister"], NPC, 20342 };
		{ GREY..INDENT..AtlasLocale["Zixil <Aspiring Merchant>"], NPC, 20419 };
		{ GREY..INDENT..AtlasLocale["Overwatch Mark 0 <Protector>"], NPC, 20420 };
		{ "" };
		{ ORNG..AtlasLocale["Southshore Inn"] };
		{ GREY..INDENT..AtlasLocale["Captain Edward Hanes"], NPC, 20400 };
		{ GREY..INDENT..AtlasLocale["Captain Sanders"], NPC, 20351 };
		{ GREY..INDENT..AtlasLocale["Commander Mograine"], NPC, 20345 };
		{ GREY..INDENT..AtlasLocale["Isillien"], NPC, 20346 };
		{ GREY..INDENT..AtlasLocale["Abbendis"], NPC, 20347 };
		{ GREY..INDENT..AtlasLocale["Fairbanks"], NPC, 20348 };
		{ GREY..INDENT..AtlasLocale["Tirion Fordring"], NPC, 20349 };
		{ GREY..INDENT..AtlasLocale["Arcanist Doan"], NPC, 20352 };
		{ GREY..INDENT..AtlasLocale["Taelan"].." ("..AtlasLocale["Upstairs"]..")", NPC, 20361 };
		{ GREY..INDENT..AtlasLocale["Barkeep Kelly <Bartender>"], NPC, 20377 };
		{ GREY..INDENT..AtlasLocale["Frances Lin <Barmaid>"], NPC, 20401 };
		{ GREY..INDENT..AtlasLocale["Chef Jessen <Speciality Meat & Slop>"], NPC, 20378 };
		{ GREY..INDENT..AtlasLocale["Stalvan Mistmantle"].." ("..AtlasLocale["Upstairs"]..")", NPC, 20355 };
		{ GREY..INDENT..AtlasLocale["Phin Odelic <The Kirin Tor>"].." ("..AtlasLocale["Upstairs"]..")", NPC, 20370 };
		{ "" };
		{ ORNG..AtlasLocale["Southshore Town Hall"] };
		{ GREY..INDENT..AtlasLocale["Magistrate Henry Maleb"], NPC, 20373 };
		{ GREY..INDENT..AtlasLocale["Raleigh the True"], NPC, 20380 };
		{ GREY..INDENT..AtlasLocale["Nathanos Marris"], NPC, 20354 };
		{ GREY..INDENT..AtlasLocale["Bilger the Straight-laced"], NPC, 20379 };
		{ "" };
		{ ORNG..AtlasLocale["Tarren Mill"] };
		{ GREY..INDENT..AtlasLocale["Innkeeper Monica"], NPC, 18649 };
		{ GREY..INDENT..AtlasLocale["Julie Honeywell"], NPC, 18656 };
		{ GREY..INDENT..AtlasLocale["Jay Lemieux"], NPC, 18655 };
		{ GREY..INDENT..AtlasLocale["Young Blanchy"], NPC, 18651 };
	};

--************************************************
-- Eastern Kingdoms Instances
--************************************************
	
	BlackrockDepths = {
		ZoneName = { AtlasLocale["Blackrock Depths"], 1584 };
		Acronym = AtlasLocale["BRD"];
		Location = { AtlasLocale["Blackrock Mountain"], 25 };
		LevelRange = "52-58";
		PlayerLimit = "5";
		Continent = AtlasLocale["Eastern Kingdoms"];
		{ ORNG..AtlasLocale["Key"]..": "..AtlasLocale["Shadowforge Key"], ITEM, 11000 };
		{ ORNG..AtlasLocale["Key"]..": "..AtlasLocale["Prison Cell Key"].." ("..AtlasLocale["Jail Break!"]..")", ITEM, 11140 };
		{ ORNG..AtlasLocale["Key"]..": "..AtlasLocale["Banner of Provocation"].." ("..AtlasLocale["Theldren"]..")", ITEM, 21986 };
		{ BLUE.."A) "..AtlasLocale["Entrance"] };
		{ GREY.."1) "..AtlasLocale["Lord Roccor"], NPC, 9025 };
		{ GREY.."2) "..AtlasLocale["Kharan Mighthammer"], NPC, 9021 };
		{ GREY.."3) "..AtlasLocale["Commander Gor'shak <Kargath Expeditionary Force>"], NPC, 9020 };
		{ GREY.."4) "..AtlasLocale["Marshal Windsor"], NPC, 9023 };
		{ GREY.."5) "..AtlasLocale["High Interrogator Gerstahn <Twilight's Hammer Interrogator>"], NPC, 9018 };
		{ GREY.."6) "..AtlasLocale["Ring of Law"] };
		{ GREY..INDENT..AtlasLocale["Anub'shiah"].." ("..AtlasLocale["Random"]..")", NPC, 9031 };
		{ GREY..INDENT..AtlasLocale["Eviscerator"].." ("..AtlasLocale["Random"]..")", NPC, 9029 };
		{ GREY..INDENT..AtlasLocale["Gorosh the Dervish"].." ("..AtlasLocale["Random"]..")", NPC, 9027 };
		{ GREY..INDENT..AtlasLocale["Grizzle"].." ("..AtlasLocale["Random"]..")", NPC, 9028 };
		{ GREY..INDENT..AtlasLocale["Hedrum the Creeper"].." ("..AtlasLocale["Random"]..")", NPC, 9032 };
		{ GREY..INDENT..AtlasLocale["Ok'thor the Breaker"].." ("..AtlasLocale["Random"]..")", NPC, 9030 };
		{ GREY..INDENT..AtlasLocale["Theldren"].." ("..AtlasLocale["Summon"]..")", NPC, 16059 };
		{ GREY..INDENT..AtlasLocale["Lefty"], NPC, 16049 };
		{ GREY..INDENT..AtlasLocale["Malgen Longspear"], NPC, 16052 };
		{ GREY..INDENT..AtlasLocale["Gnashjaw <Malgen Longspear's Pet>"], NPC, 16095 };
		{ GREY..INDENT..AtlasLocale["Rotfang"], NPC, 16050 };
		{ GREY..INDENT..AtlasLocale["Va'jashni"], NPC, 16055 };
		{ GREY..INDENT..AtlasLocale["Houndmaster Grebmar"].." ("..AtlasLocale["Lower"]..")", NPC, 9319 };
		{ GREY..INDENT..AtlasLocale["Elder Morndeep"].." ("..AtlasLocale["Lunar"]..")", NPC, 15549 };
		{ GREY..INDENT..AtlasLocale["High Justice Grimstone"], NPC, 10096 };
		{ GREY.."7) "..AtlasLocale["Monument of Franclorn Forgewright"], OBJECT, 164689 };
		{ GREY..INDENT..AtlasLocale["Pyromancer Loregrain"], NPC, 9024 };
		{ GREY.."8) "..AtlasLocale["The Vault"] };
		{ GREY..INDENT..AtlasLocale["Warder Stilgiss"], NPC, 9041 };
		{ GREY..INDENT..AtlasLocale["Verek"], NPC, 9042 };
		{ GREY..INDENT..AtlasLocale["Watchman Doomgrip"], NPC, 9476 };
		{ GREY.."9) "..AtlasLocale["Fineous Darkvire <Chief Architect>"], NPC, 9056 };
		{ GREY.."10) "..AtlasLocale["The Black Anvil"] };
		{ GREY..INDENT..AtlasLocale["Lord Incendius"], NPC, 9017 };
		{ GREY.."11) "..AtlasLocale["Bael'Gar"], NPC, 9016 };
		{ GREY.."12) "..AtlasLocale["Shadowforge Lock"] };
		{ GREY.."13) "..AtlasLocale["General Angerforge"], NPC, 9033 };
		{ GREY.."14) "..AtlasLocale["Golem Lord Argelmach"], NPC, 8983 };
		{ GREY..INDENT..AtlasLocale["Field Repair Bot 74A"], NPC, 14337 };
		{ GREY..INDENT..AtlasLocale["Blacksmithing Plans"], OBJECT, 173232 };
		{ GREY.."15) "..AtlasLocale["The Grim Guzzler"] };
		{ GREY..INDENT..AtlasLocale["Hurley Blackbreath"], NPC, 9537 };
		{ GREY..INDENT..AtlasLocale["Lokhtos Darkbargainer <The Thorium Brotherhood>"], NPC, 12944 };
		{ GREY..INDENT..AtlasLocale["Mistress Nagmara"], NPC, 9500 };
		{ GREY..INDENT..AtlasLocale["Phalanx"], NPC, 9502 };
		{ GREY..INDENT..AtlasLocale["Plugger Spazzring"], NPC, 9499 };
		{ GREY..INDENT..AtlasLocale["Private Rocknot"], NPC, 9503 };
		{ GREY..INDENT..AtlasLocale["Ribbly Screwspigot"], NPC, 9543 };
		{ GREY..INDENT..AtlasLocale["Coren Direbrew"].." ("..AtlasLocale["Brewfest"]..")", NPC, 23872 };
		{ GREY.."16) "..AtlasLocale["Ambassador Flamelash"], NPC, 9156 };
		{ GREY.."17) "..AtlasLocale["Panzor the Invincible"].." ("..AtlasLocale["Rare"]..")", NPC, 8923 };
		{ GREY..INDENT..AtlasLocale["Blacksmithing Plans"], OBJECT, 173232 };
		{ GREY.."18) "..AtlasLocale["Summoner's Tomb"] };
		{ GREY.."19) "..AtlasLocale["The Lyceum"] };
		{ GREY.."20) "..AtlasLocale["Magmus"], NPC, 9938 };
		{ GREY.."21) "..AtlasLocale["Emperor Dagran Thaurissan"], NPC, 9019 };
		{ GREY..INDENT..AtlasLocale["Princess Moira Bronzebeard <Princess of Ironforge>"], NPC, 8929 };
		{ GREY..INDENT..AtlasLocale["High Priestess of Thaurissan"], NPC, 10076 };
		{ GREY.."22) "..AtlasLocale["The Black Forge"] };
		{ GREY.."23) "..AtlasLocale["Molten Core"], ZONE, 2717 };
		{ GREY..INDENT..AtlasLocale["Core Fragment"], OBJECT, 179553 };
		{ GREY.."24) "..AtlasLocale["Overmaster Pyron"], NPC, 9026 };
		{ GREY.."25) "..AtlasLocale["Blacksmithing Plans"], OBJECT, 173232 };
	};
	BlackrockSpireLower = {
		ZoneName = { AtlasLocale["Blackrock Spire"].." ("..AtlasLocale["Lower"]..")", 1583 };
		Acronym = AtlasLocale["LBRS"];
		Location = { AtlasLocale["Blackrock Mountain"], 25 };
		LevelRange = "54-60";
		PlayerLimit = "10";
		Continent = AtlasLocale["Eastern Kingdoms"];
		{ ORNG..AtlasLocale["Key"]..": "..AtlasLocale["Brazier of Invocation"].." ("..AtlasLocale["DS2"]..")", ITEM, 22057 };
		{ BLUE.."A) "..AtlasLocale["Entrance"] };
		{ BLUE.."B) "..AtlasLocale["Blackrock Spire"].." ("..AtlasLocale["Upper"]..")", ZONE, 1583 };
		{ BLUE.."C-F) "..AtlasLocale["Connections"] };
		{ GREY.."1) "..AtlasLocale["Vaelan"].." ("..AtlasLocale["Upper"]..")", NPC, 10296 };
		{ GREY.."2) "..AtlasLocale["Warosh <The Cursed>"].." ("..AtlasLocale["Wanders"]..")", NPC, 10799 };
		{ GREY..INDENT..AtlasLocale["Elder Stonefort"], NPC, 15560 };
		{ GREY.."3) "..AtlasLocale["Roughshod Pike"], OBJECT, 175886 };
		{ GREY.."4) "..AtlasLocale["Spirestone Butcher"].." ("..AtlasLocale["Rare"]..")", NPC, 9219 };
		{ GREY.."5) "..AtlasLocale["Highlord Omokk"], NPC, 9196 };
		{ GREY.."6) "..AtlasLocale["Spirestone Battle Lord"].." ("..AtlasLocale["Rare"]..")", NPC, 9218 };
		{ GREY..INDENT..AtlasLocale["Spirestone Lord Magus"].." ("..AtlasLocale["Rare"]..")", NPC, 9217 };
		{ GREY.."7) "..AtlasLocale["Shadow Hunter Vosh'gajin"], NPC, 9236 };
		{ GREY..INDENT..AtlasLocale["Fifth Mosh'aru Tablet"], OBJECT, 175949 };
		{ GREY.."8) "..AtlasLocale["Bijou"], NPC, 10257 };
		{ GREY.."9) "..AtlasLocale["War Master Voone"], NPC, 9237 };
		{ GREY..INDENT..AtlasLocale["Mor Grayhoof"].." ("..AtlasLocale["Summon"]..")", NPC, 16080 };
		{ GREY..INDENT..AtlasLocale["Sixth Mosh'aru Tablet"], OBJECT, 175950 };
		{ GREY.."10) "..AtlasLocale["Bijou's Belongings"], OBJECT, 175334 };
		{ GREY.."11) "..AtlasLocale["Human Remains"].." ("..AtlasLocale["Lower"]..")", OBJECT, 176090 };
		{ GREY..INDENT..AtlasLocale["Unfired Plate Gauntlets"].." ("..AtlasLocale["Lower"]..")", OBJECT, 176089 };
		{ GREY.."12) "..AtlasLocale["Bannok Grimaxe <Firebrand Legion Champion>"].." ("..AtlasLocale["Rare"]..")", NPC, 9596 };
		{ GREY.."13) "..AtlasLocale["Mother Smolderweb"], NPC, 10596 };
		{ GREY.."14) "..AtlasLocale["Crystal Fang"].." ("..AtlasLocale["Rare"]..")", NPC, 10376 };
		{ GREY.."15) "..AtlasLocale["Urok's Tribute Pile"], OBJECT, 175621 };
		{ GREY..INDENT..AtlasLocale["Urok Doomhowl"].." ("..AtlasLocale["Summon"]..")", NPC, 10584 };
		{ GREY.."16) "..AtlasLocale["Quartermaster Zigris <Bloodaxe Legion>"], NPC, 9736 };
		{ GREY.."17) "..AtlasLocale["Halycon"], NPC, 10220 };
		{ GREY..INDENT..AtlasLocale["Gizrul the Slavener"], NPC, 10268 };
		{ GREY.."18) "..AtlasLocale["Ghok Bashguud <Bloodaxe Champion>"].." ("..AtlasLocale["Rare"]..")", NPC, 9718 };
		{ GREY.."19) "..AtlasLocale["Overlord Wyrmthalak"], NPC, 9568 };
		{ GREN.."1') "..AtlasLocale["Burning Felguard"].." ("..AtlasLocale["Rare"]..", "..AtlasLocale["Summon"]..")", NPC, 10263 };
	};
	BlackrockSpireUpper = {
		ZoneName = { AtlasLocale["Blackrock Spire"].." ("..AtlasLocale["Upper"]..")", 1583 };
		Acronym = AtlasLocale["UBRS"];
		Location = { AtlasLocale["Blackrock Mountain"], 25 };
		LevelRange = "56-61";
		PlayerLimit = "10";
		Continent = AtlasLocale["Eastern Kingdoms"];
		{ ORNG..AtlasLocale["Key"]..": "..AtlasLocale["Seal of Ascension"], ITEM, 12344 };
		{ ORNG..AtlasLocale["Key"]..": "..AtlasLocale["Brazier of Invocation"].." ("..AtlasLocale["DS2"]..")", ITEM, 22057 };
		{ BLUE.."A) "..AtlasLocale["Entrance"] };
		{ BLUE.."B) "..AtlasLocale["Blackrock Spire"].." ("..AtlasLocale["Lower"]..")", ZONE, 1583 };
		{ BLUE.."C-E) "..AtlasLocale["Connections"] };
		{ GREY.."1) "..AtlasLocale["Pyroguard Emberseer"], NPC, 9816 };
		{ GREY.."2) "..AtlasLocale["Solakar Flamewreath"], NPC, 10264 };
		{ GREY..INDENT..AtlasLocale["Father Flame"], OBJECT, 175245 };
		{ GREY.."3) "..AtlasLocale["Darkstone Tablet"], OBJECT, 175385 };
		{ GREY..INDENT..AtlasLocale["Doomrigger's Coffer"], OBJECT, 175382 };
		{ GREY.."4) "..AtlasLocale["Jed Runewatcher <Blackhand Legion>"].." ("..AtlasLocale["Rare"]..")", NPC, 10509 };
		{ GREY.."5) "..AtlasLocale["Goraluk Anvilcrack <Blackhand Legion Armorsmith>"], NPC, 10899 };
		{ GREY.."6) "..AtlasLocale["Warchief Rend Blackhand"], NPC, 10429 };
		{ GREY..INDENT..AtlasLocale["Gyth <Rend Blackhand's Mount>"], NPC, 10339 };
		{ GREY.."7) "..AtlasLocale["Awbee"], NPC, 10740 };
		{ GREY.."8) "..AtlasLocale["The Beast"], NPC, 10430 };
		{ GREY..INDENT..AtlasLocale["Lord Valthalak"].." ("..AtlasLocale["Summon"]..")", NPC, 16042 };
		{ GREY..INDENT..AtlasLocale["Finkle Einhorn"], NPC, 10776 };
		{ GREY.."9) "..AtlasLocale["General Drakkisath"], NPC, 10363 };
		{ GREY..INDENT..AtlasLocale["Drakkisath's Brand"], OBJECT, 179880 };
		{ GREY.."10) "..AtlasLocale["Blackwing Lair"], ZONE, 2677 };
	};
	BlackwingLair = {
		ZoneName = { AtlasLocale["Blackwing Lair"], 2677 };
		Acronym = AtlasLocale["BWL"];
		Location = { AtlasLocale["Blackrock Spire"], 1583 };
		LevelRange = "60-70";
		PlayerLimit = "40";
		Continent = AtlasLocale["Eastern Kingdoms"];
		{ ORNG..AtlasLocale["Attunement Required"] };
		{ BLUE.."A) "..AtlasLocale["Entrance"] };
		{ BLUE.."B) "..AtlasLocale["Connects"] };
		{ BLUE.."C) "..AtlasLocale["Connects"] };
		{ GREY.."1) "..AtlasLocale["Razorgore the Untamed"], NPC, 12435 };
		{ GREY.."2) "..AtlasLocale["Vaelastrasz the Corrupt"], NPC, 13020 };
		{ GREY.."3) "..AtlasLocale["Broodlord Lashlayer"], NPC, 12017 };
		{ GREY.."4) "..AtlasLocale["Firemaw"], NPC, 11983 };
		{ GREY..INDENT..AtlasLocale["Draconic for Dummies (Chapter VII)"], ITEM, 21109 };
		{ GREY.."5) "..AtlasLocale["Master Elemental Shaper Krixix"], NPC, 14401 };
		{ GREY.."6) "..AtlasLocale["Ebonroc"], NPC, 14601 };
		{ GREY.."7) "..AtlasLocale["Flamegor"], NPC, 11981 };
		{ GREY.."8) "..AtlasLocale["Chromaggus"], NPC, 14020 };
		{ GREY.."9) "..AtlasLocale["Nefarian"], NPC, 11583 };
	};
	Gnomeregan = {
		ZoneName = { AtlasLocale["Gnomeregan"], 133 };
		Acronym = AtlasLocale["Gnome"];
		Location = { AtlasLocale["Dun Morogh"], 1 };
		LevelRange = "24-32";
		PlayerLimit = "10";
		Continent = AtlasLocale["Eastern Kingdoms"];
		{ ORNG..AtlasLocale["Key"]..": "..AtlasLocale["Workshop Key"].." ("..AtlasLocale["Back Door"]..")", ITEM, 6893 };
		{ BLUE.."A) "..AtlasLocale["Entrance"].." ("..AtlasLocale["Front Door"]..")" };
		{ BLUE.."B) "..AtlasLocale["Entrance"].." ("..AtlasLocale["Back Door"]..")" };
		{ GREY.."1) "..AtlasLocale["Blastmaster Emi Shortfuse"], NPC, 7998 };
		{ GREY..INDENT..AtlasLocale["Grubbis"], NPC, 7361 };
		{ GREY..INDENT..AtlasLocale["Chomper"], NPC, 6215 };
		{ GREY.."2) "..AtlasLocale["Clean Room"] };
		{ GREY..INDENT..AtlasLocale["Tink Sprocketwhistle <Engineering Supplies>"], NPC, 9676 };
		{ GREY..INDENT..AtlasLocale["The Sparklematic 5200"], OBJECT, 142487 };
		{ GREY..INDENT..AtlasLocale["Mail Box"] };
		{ GREY.."3) "..AtlasLocale["Kernobee"], NPC, 7850 };
		{ GREY..INDENT..AtlasLocale["Alarm-a-bomb 2600"], NPC, 7897 };
		{ GREY..INDENT..AtlasLocale["Matrix Punchograph 3005-B"], OBJECT, 142475 };
		{ GREY.."4) "..AtlasLocale["Viscous Fallout"], NPC, 7079 };
		{ GREY.."5) "..AtlasLocale["Electrocutioner 6000"], NPC, 6235 };
		{ GREY..INDENT..AtlasLocale["Matrix Punchograph 3005-C"], OBJECT, 142476 };
		{ GREY.."6) "..AtlasLocale["Crowd Pummeler 9-60"].." ("..AtlasLocale["Upper"]..")", NPC, 6229 };
		{ GREY..INDENT..AtlasLocale["Matrix Punchograph 3005-D"], OBJECT, 142696 };
		{ GREY.."7) "..AtlasLocale["Dark Iron Ambassador"], NPC, 6228 };
		{ GREY.."8) "..AtlasLocale["Mekgineer Thermaplugg"], NPC, 7800 };
	};
	MoltenCore = {
		ZoneName = { AtlasLocale["Molten Core"], 2717 };
		Acronym = AtlasLocale["MC"];
		Location = { AtlasLocale["Blackrock Depths"], 1584 };
		LevelRange = "60-70";
		PlayerLimit = "10";
		Continent = AtlasLocale["Eastern Kingdoms"];
		{ ORNG..AtlasLocale["Attunement Required"] };
		{ ORNG..AtlasLocale["Rep"]..": "..AtlasLocale["Hydraxian Waterlords"], FACTION, 749 };
		{ ORNG..AtlasLocale["Key"]..": "..AtlasLocale["Aqual Quintessence"].." ("..AtlasLocale["Boss"]..")", ITEM, 17333 };
		{ ORNG..AtlasLocale["Key"]..": "..AtlasLocale["Eternal Quintessence"].." ("..AtlasLocale["Boss"]..")", ITEM, 22754 };
		{ BLUE.."A) "..AtlasLocale["Entrance"] };
		{ GREY.."1) "..AtlasLocale["Lucifron"], NPC, 12118 };
		{ GREY.."2) "..AtlasLocale["Magmadar"], NPC, 11982 };
		{ GREY.."3) "..AtlasLocale["Gehennas"], NPC, 12259 };
		{ GREY.."4) "..AtlasLocale["Garr"], NPC, 12057 };
		{ GREY.."5) "..AtlasLocale["Shazzrah"], NPC, 12264 };
		{ GREY.."6) "..AtlasLocale["Baron Geddon"], NPC, 12056 };
		{ GREY.."7) "..AtlasLocale["Golemagg the Incinerator"], NPC, 11988 };
		{ GREY.."8) "..AtlasLocale["Sulfuron Harbinger"], NPC, 12098 };
		{ GREY.."9) "..AtlasLocale["Majordomo Executus"], NPC, 12018 };
		{ GREY.."10) "..AtlasLocale["Ragnaros"], NPC, 11502 };
	};
	SMLibrary = {
		ZoneName = { AtlasLocale["SM: Library"], 796 };
		Acronym = AtlasLocale["Lib"];
		Location = { AtlasLocale["Scarlet Monastery, Tirisfal Glades"], 85 };
		LevelRange = "31-37";
		PlayerLimit = "10";
		Continent = AtlasLocale["Eastern Kingdoms"];
		{ BLUE.."A) "..AtlasLocale["Entrance"] };
		{ GREY.."1) "..AtlasLocale["Houndmaster Loksey"], NPC, 3974 };
		{ GREY.."2) "..AtlasLocale["Arcanist Doan"], NPC, 6487 };
	};
	SMArmory = {
		ZoneName = { AtlasLocale["SM: Armory"], 796 };
		Acronym = AtlasLocale["Armory"];
		Location = { AtlasLocale["Scarlet Monastery, Tirisfal Glades"], 85 };
		LevelRange = "33-40";
		PlayerLimit = "10";
		Continent = AtlasLocale["Eastern Kingdoms"];
		{ ORNG..AtlasLocale["Key"]..": "..AtlasLocale["The Scarlet Key"], ITEM, 7146 };
		{ BLUE.."A) "..AtlasLocale["Entrance"] };
		{ GREY.."1) "..AtlasLocale["Herod <The Scarlet Champion>"], NPC, 3975 };
	};
	SMCathedral = {
		ZoneName = { AtlasLocale["SM: Cathedral"], 796 };
		Acronym = AtlasLocale["Cath"];
		Location = { AtlasLocale["Scarlet Monastery, Tirisfal Glades"], 85 };
		LevelRange = "36-42";
		PlayerLimit = "10";
		Continent = AtlasLocale["Eastern Kingdoms"];
		{ ORNG..AtlasLocale["Key"]..": "..AtlasLocale["The Scarlet Key"], ITEM, 7146 };
		{ BLUE.."A) "..AtlasLocale["Entrance"] };
		{ GREY.."1) "..AtlasLocale["High Inquisitor Fairbanks"], NPC, 4542 };
		{ GREY.."2) "..AtlasLocale["Scarlet Commander Mograine"], NPC, 3976 };
		{ GREY..INDENT..AtlasLocale["High Inquisitor Whitemane"], NPC, 3977 };
	};
	SMGraveyard = {
		ZoneName = { AtlasLocale["SM: Graveyard"], 796 };
		Acronym = AtlasLocale["GY"];
		Location = { AtlasLocale["Scarlet Monastery, Tirisfal Glades"], 85 };
		LevelRange = "28-35";
		PlayerLimit = "10";
		Continent = AtlasLocale["Eastern Kingdoms"];
		{ BLUE.."A) "..AtlasLocale["Entrance"] };
		{ GREY.."1) "..AtlasLocale["Interrogator Vishas"], NPC, 3983 };
		{ GREY..INDENT..AtlasLocale["Vorrel Sengutz"], NPC, 3981 };
		{ GREY.."2) "..AtlasLocale["Pumpkin Shrine"].." ("..AtlasLocale["Hallow's End"]..")", OBJECT, 186267 };
		{ GREY..INDENT..AtlasLocale["Headless Horseman"].." ("..AtlasLocale["Summon"]..")", NPC, 23682 };
		{ GREY.."3) "..AtlasLocale["Bloodmage Thalnos"], NPC, 4543 };
		{ GREN.."1') "..AtlasLocale["Ironspine"].." ("..AtlasLocale["Rare"]..")", NPC, 6489 };
		{ GREN..INDENT..AtlasLocale["Azshir the Sleepless"].." ("..AtlasLocale["Rare"]..")", NPC, 6490 };
		{ GREN..INDENT..AtlasLocale["Fallen Champion"].." ("..AtlasLocale["Rare"]..")", NPC, 6488 };
	};
	Scholomance = {
		ZoneName = { AtlasLocale["Scholomance"], 2057 };
		Acronym = AtlasLocale["Scholo"];
		Location = { AtlasLocale["Western Plaguelands"], 28 };
		LevelRange = "58-60";
		PlayerLimit = "5";
		Continent = AtlasLocale["Eastern Kingdoms"];
		{ ORNG..AtlasLocale["Rep"]..": "..AtlasLocale["Argent Dawn"], FACTION, 529 };
		{ ORNG..AtlasLocale["Key"]..": "..AtlasLocale["Skeleton Key"], ITEM, 13704 };
		{ ORNG..AtlasLocale["Key"]..": "..AtlasLocale["Viewing Room Key (Viewing Room)"], ITEM, 13873 };
		{ ORNG..AtlasLocale["Key"]..": "..AtlasLocale["Blood of Innocents (Kirtonos)"], ITEM, 13523 };
		{ ORNG..AtlasLocale["Key"]..": "..AtlasLocale["Brazier of Invocation"].." ("..AtlasLocale["DS2"]..")", ITEM, 22057 };
		{ ORNG..AtlasLocale["Key"]..": "..AtlasLocale["Divination Scryer (Darkreaver)"], ITEM, 18746 };
		{ BLUE.."A) "..AtlasLocale["Entrance"] };
		{ BLUE.."B) "..AtlasLocale["Stairway"] };
		{ BLUE.."C) "..AtlasLocale["Stairway"] };
		{ GREY.."1) "..AtlasLocale["Blood Steward of Kirtonos"], NPC, 14861 };
		{ GREY..INDENT..AtlasLocale["The Deed to Southshore"], OBJECT, 176486 };
		{ GREY.."2) "..AtlasLocale["Kirtonos the Herald"].." ("..AtlasLocale["Summon"]..")", NPC, 10506 };
		{ GREY.."3) "..AtlasLocale["Jandice Barov"], NPC, 10503 };
		{ GREY.."4) "..AtlasLocale["The Deed to Tarren Mill"], OBJECT, 176487 };
		{ GREY.."5) "..AtlasLocale["Rattlegore"].." ("..AtlasLocale["Lower"]..")", NPC, 11622 };
		{ GREY..INDENT..AtlasLocale["Death Knight Darkreaver"].." ("..AtlasLocale["Summon"]..")", NPC, 14516 };
		{ GREY.."6) "..AtlasLocale["Marduk Blackpool"], NPC, 10433 };
		{ GREY..INDENT..AtlasLocale["Vectus"], NPC, 10432 };
		{ GREY.."7) "..AtlasLocale["Ras Frostwhisper"], NPC, 10508 };
		{ GREY..INDENT..AtlasLocale["The Deed to Brill"], OBJECT, 176484 };
		{ GREY..INDENT..AtlasLocale["Kormok"].." ("..AtlasLocale["Summon"]..")", NPC, 16118 };
		{ GREY.."8) "..AtlasLocale["Instructor Malicia"], NPC, 10505 };
		{ GREY.."9) "..AtlasLocale["Doctor Theolen Krastinov <The Butcher>"], NPC, 11261 };
		{ GREY.."10) "..AtlasLocale["Lorekeeper Polkelt"], NPC, 10901 };
		{ GREY.."11) "..AtlasLocale["The Ravenian"], NPC, 10507 };
		{ GREY.."12) "..AtlasLocale["Lord Alexei Barov"], NPC, 10504 };
		{ GREY..INDENT..AtlasLocale["The Deed to Caer Darrow"], OBJECT, 176485 };
		{ GREY.."13) "..AtlasLocale["Lady Illucia Barov"], NPC, 10502 };
		{ GREY.."14) "..AtlasLocale["Darkmaster Gandling"], NPC, 1853 };
		{ GREN.."1') "..AtlasLocale["Torch Lever"] };
		{ GREN.."2') "..AtlasLocale["Secret Chest"] };
		{ GREN.."3') "..AtlasLocale["Alchemy Lab"] };
	};
	ShadowfangKeep = {
		ZoneName = { AtlasLocale["Shadowfang Keep"], 209 };
		Acronym = AtlasLocale["SFK"];
		Location = { AtlasLocale["Silverpine Forest"], 130 };
		LevelRange = "17-25";
		PlayerLimit = "10";
		Continent = AtlasLocale["Eastern Kingdoms"];
		{ BLUE.."A) "..AtlasLocale["Entrance"] };
		{ GREY.."1) "..AtlasLocale["Rethilgore <The Cell Keeper>"], NPC, 3914 };
		{ GREY..INDENT..AtlasLocale["Sorcerer Ashcrombe"], NPC, 3850 };
		{ GREY..INDENT..AtlasLocale["Deathstalker Adamant"], NPC, 3849 };
		{ GREY..INDENT..AtlasLocale["Landen Stilwell"], NPC, 17822 };
		{ GREY.."2) "..AtlasLocale["Deathstalker Vincent"], NPC, 4444 };
		{ GREY.."3) "..AtlasLocale["Fel Steed"], NPC, 3864 };
		{ GREY..INDENT..AtlasLocale["Jordan's Hammer"], OBJECT, 91138 };
		{ GREY..INDENT..AtlasLocale["Crate of Ingots"], OBJECT, 182011 };
		{ GREY.."4) "..AtlasLocale["Razorclaw the Butcher"], NPC, 3886 };
		{ GREY.."5) "..AtlasLocale["Baron Silverlaine"], NPC, 3887 };
		{ GREY.."6) "..AtlasLocale["Commander Springvale"], NPC, 4278 };
		{ GREY.."7) "..AtlasLocale["Odo the Blindwatcher"], NPC, 4279 };
		{ GREY.."8) "..AtlasLocale["Deathsworn Captain"].." ("..AtlasLocale["Rare"]..")", NPC, 3872 };
		{ GREY.."9) "..AtlasLocale["Fenrus the Devourer"], NPC, 4274 };
		{ GREY..INDENT..AtlasLocale["Arugal's Voidwalker"], NPC, 4627 };
		{ GREY..INDENT..AtlasLocale["The Book of Ur"], OBJECT, 36738 };
		{ GREY.."10) "..AtlasLocale["Wolf Master Nandos"], NPC, 3927 };
		{ GREY.."11) "..AtlasLocale["Archmage Arugal"], NPC, 4275 };
	};
	Stratholme = {
		ZoneName = { AtlasLocale["Stratholme"], 2017 };
		Acronym = AtlasLocale["Strat"];
		Location = { AtlasLocale["Eastern Plaguelands"], 139 };
		LevelRange = "58-60";
		PlayerLimit = "5";
		Continent = AtlasLocale["Eastern Kingdoms"];
		{ ORNG..AtlasLocale["Rep"]..": "..AtlasLocale["Argent Dawn"], FACTION, 529 };
		{ ORNG..AtlasLocale["Key"]..": "..AtlasLocale["The Scarlet Key"].." ("..AtlasLocale["Living Side"]..")", ITEM, 7146 };
		{ ORNG..AtlasLocale["Key"]..": "..AtlasLocale["Key to the City"].." ("..AtlasLocale["Undead Side"]..")", ITEM, 12382 };
		{ ORNG..AtlasLocale["Key"]..": "..AtlasLocale["Various Postbox Keys"].." ("..AtlasLocale["Postmaster"]..")" };
		{ ORNG..AtlasLocale["Key"]..": "..AtlasLocale["Brazier of Invocation"].." ("..AtlasLocale["DS2"]..")", ITEM, 22057 };
		{ BLUE.."A) "..AtlasLocale["Entrance"].." ("..AtlasLocale["Front"]..")" };
		{ BLUE.."B) "..AtlasLocale["Entrance"].." ("..AtlasLocale["Side"]..")" };
		{ GREY.."1) "..AtlasLocale["Skul"].." ("..AtlasLocale["Rare"]..", "..AtlasLocale["Varies"]..")", NPC, 10393 };
		{ GREY..INDENT..AtlasLocale["Stratholme Courier"], NPC, 11082 };
		{ GREY..INDENT..AtlasLocale["Fras Siabi"], NPC, 11058 };
		{ GREY.."2) "..AtlasLocale["Atiesh <Hand of Sargeras>"].." ("..AtlasLocale["Summon"]..")", NPC, 16387 };
		{ GREY.."3) "..AtlasLocale["Hearthsinger Forresten"].." ("..AtlasLocale["Varies"]..")", NPC, 10558 };
		{ GREY.."4) "..AtlasLocale["The Unforgiven"], NPC, 10516 };
		{ GREY.."5) "..AtlasLocale["Elder Farwhisper"].." ("..AtlasLocale["Lunar"]..")", NPC, 15607 };
		{ GREY.."6) "..AtlasLocale["Timmy the Cruel"], NPC, 10808 };
		{ GREY.."7) "..AtlasLocale["Malor the Zealous"], NPC, 11032 };
		{ GREY..INDENT..AtlasLocale["Malor's Strongbox"], OBJECT, 176112 };
		{ GREY.."8) "..AtlasLocale["Crimson Hammersmith"].." ("..AtlasLocale["Summon"]..")", NPC, 11120 };
		{ GREY..INDENT..AtlasLocale["Blacksmithing Plans"], OBJECT, 173232 };
		{ GREY.."9) "..AtlasLocale["Cannon Master Willey"], NPC, 10997 };
		{ GREY.."10) "..AtlasLocale["Archivist Galford"], NPC, 10811 };
		{ GREY.."11) "..AtlasLocale["Grand Crusader Dathrohan"], NPC, 10812 };
		{ GREY..INDENT..AtlasLocale["Balnazzar"], NPC, 10813 };
		{ GREY..INDENT..AtlasLocale["Sothos"].." ("..AtlasLocale["Summon"]..")", NPC, 16102 };
		{ GREY..INDENT..AtlasLocale["Jarien"].." ("..AtlasLocale["Summon"]..")", NPC, 16101 };
		{ GREY.."12) "..AtlasLocale["Magistrate Barthilas"].." ("..AtlasLocale["Varies"]..")", NPC, 10435 };
		{ GREY.."13) "..AtlasLocale["Aurius"], NPC, 10917 };
		{ GREY.."14) "..AtlasLocale["Stonespine"].." ("..AtlasLocale["Rare"]..")", NPC, 10809 };
		{ GREY.."15) "..AtlasLocale["Baroness Anastari"], NPC, 10436 };
		{ GREY..INDENT..AtlasLocale["Black Guard Swordsmith"].." ("..AtlasLocale["Summon"]..")", NPC, 11121 };
		{ GREY..INDENT..AtlasLocale["Blacksmithing Plans"], OBJECT, 173232 };
		{ GREY.."16) "..AtlasLocale["Nerub'enkan"], NPC, 10437 };
		{ GREY.."17) "..AtlasLocale["Maleki the Pallid"], NPC, 10438 };
		{ GREY.."18) "..AtlasLocale["Ramstein the Gorger"], NPC, 10439 };
		{ GREY.."19) "..AtlasLocale["Baron Rivendare"], NPC, 10440 };
		{ GREY..INDENT..AtlasLocale["Ysida Harmon"], NPC, 16031 };
		{ GREN.."1') "..AtlasLocale["Crusaders' Square Postbox"] };
		{ GREN.."2') "..AtlasLocale["Market Row Postbox"] };
		{ GREN.."3') "..AtlasLocale["Festival Lane Postbox"] };
		{ GREN.."4') "..AtlasLocale["Elders' Square Postbox"] };
		{ GREN.."5') "..AtlasLocale["King's Square Postbox"] };
		{ GREN.."6') "..AtlasLocale["Fras Siabi's Postbox"] };
		{ GREN..AtlasLocale["3rd Box Opened: Postmaster Malown"], NPC, 11143 };
	};
	TheDeadmines = {
		ZoneName = { "The Deadmines", 1581 };
		Acronym = "VC";
		Location = { "Westfall", 40 };
		LevelRange = "16-22";
		PlayerLimit = "10";
		Continent = "Eastern Kingdoms";
		{ BLUE.."A) Entrance" };
		{ BLUE.."B) Exit" };
		{ GREY.."1) Rhahk'Zor <The Foreman>", NPC, 644 };
		{ GREY.."2) Miner Johnson (Rare)", NPC, 3586 };
		{ GREY.."3) Sneed <Lumbermaster>", NPC, 643 };
		{ GREY..INDENT.."Sneed's Shredder <Lumbermaster>", NPC, 642 };
		{ GREY.."4) Gilnid <The Smelter>", NPC, 1763 };
		{ GREY.."5) Defias Gunpowder", OBJECT, 17155 };
		{ GREY.."6) Captain Greenskin", NPC, 647 };
		{ GREY..INDENT.."Edwin VanCleef <Defias Kingpin>", NPC, 639 };
		{ GREY..INDENT.."Mr. Smite <The Ship's First Mate>", NPC, 646 };
		{ GREY..INDENT.."Cookie <The Ship's Cook>", NPC, 645 };
	};
	TheStockade = {
		ZoneName = { "The Stockade", 717 };
		Acronym = "Stocks";
		Location = { "Stormwind City", 1519 };
		LevelRange = "21-27";
		PlayerLimit = "10";
		Continent = "Eastern Kingdoms";
		{ BLUE.."A) Entrance" };
		{ GREY.."1) Targorr the Dread (Varies)", NPC, 1696 };
		{ GREY.."2) Kam Deepfury", NPC, 1666 };
		{ GREY.."3) Hamhock", NPC, 1717 };
		{ GREY.."4) Bazil Thredd", NPC, 1716 };
		{ GREY.."5) Dextren Ward", NPC, 1663 };
		{ GREY.."6) Bruegal Ironknuckle (Rare)", NPC, 1720 };
	};
	TheSunkenTemple = {
		ZoneName = { "Sunken Temple", 1417 };
		Acronym = "ST";
		Location = { "Swamp of Sorrows", 8 };
		LevelRange = "46-53";
		PlayerLimit = "10";
		Continent = "Eastern Kingdoms";
		{ ORNG.."AKA: The Temple of Atal'Hakkar" };
		{ ORNG.."Key: Yeh'kinya's Scroll (Avatar of Hakkar)", ITEM, 10818 };
		{ BLUE.."A) Entrance" };
		{ BLUE.."B) Stairway" };
		{ BLUE.."C) Atal'ai Defenders (Upper)" };
		{ BLUE..INDENT.."Gasher", NPC, 5713 };
		{ BLUE..INDENT.."Loro", NPC, 5714 };
		{ BLUE..INDENT.."Hukku", NPC, 5715 };
		{ BLUE..INDENT.."Zolo", NPC, 5712 };
		{ BLUE..INDENT.."Mijan", NPC, 5717 };
		{ BLUE..INDENT.."Zul'Lor", NPC, 5716 };
		{ GREY.."1) Altar of Hakkar", OBJECT, 148836 };
		{ GREY..INDENT.."Atal'alarion <Guardian of the Idol>", NPC, 8580 };
		{ GREY.."2) Dreamscythe", NPC, 5721 };
		{ GREY..INDENT.."Weaver", NPC, 5720 };
		{ GREY.."3) Avatar of Hakkar", NPC, 8443 };
		{ GREY.."4) Jammal'an the Prophet", NPC, 5710 };
		{ GREY..INDENT.."Ogom the Wretched", NPC, 5711 };
		{ GREY.."5) Morphaz", NPC, 5719 };
		{ GREY..INDENT.."Hazzas", NPC, 5722 };
		{ GREY.."6) Shade of Eranikus", NPC, 5709 };
		{ GREY..INDENT.."Essence Font", OBJECT, 148512 };
		{ GREY.."7) Spawn of Hakkar (Rare)", NPC, 5708 };
		{ GREY.."8) Elder Starsong (Lunar)", NPC, 15593 };
		{ GREN.."1'-6') Statue Activation Order" };
	};
	Uldaman = {
		ZoneName = { "Uldaman", 1337 };
		Acronym = "Uld";
		Location = { "Badlands", 3 };
		LevelRange = "36-42";
		PlayerLimit = "10";
		Continent = "Eastern Kingdoms";
		{ ORNG.."Key: Staff of Prehistoria (Ironaya)", ITEM, 7733 };
		{ BLUE.."A) Entrance (Front)" };
		{ BLUE.."B) Entrance (Back)" };
		{ GREY.."1) Baelog", NPC, 6906 };
		{ GREY..INDENT.."Eric \"The Swift\"", NPC, 6907 };
		{ GREY..INDENT.."Olaf", NPC, 6908 };
		{ GREY..INDENT.."Baelog's Chest", OBJECT, 123329 };
		{ GREY..INDENT.."Conspicuous Urn", OBJECT, 125477 };
		{ GREY.."2) Remains of a Paladin", NPC, 6912 };
		{ GREY.."3) Revelosh", NPC, 6910 };
		{ GREY.."4) Ironaya", NPC, 7228 };
		{ GREY.."5) Obsidian Sentinel", NPC, 7023 };
		{ GREY.."6) Annora <Enchanting Trainer>", NPC, 11073 };
		{ GREY.."7) Ancient Stone Keeper", NPC, 7206 };
		{ GREY.."8) Galgann Firehammer", NPC, 7291 };
		{ GREY..INDENT.."Tablet of Will", OBJECT, 142088 };
		{ GREY..INDENT.."Shadowforge Cache", OBJECT, 113757 };
		{ GREY.."9) Grimlok <Stonevault Chieftain>", NPC, 4854 };
		{ GREY.."10) Archaedas <Ancient Stone Watcher> (Lower)", NPC, 2748 };
		{ GREY.."11) The Discs of Norgannon (Lower)", OBJECT, 131474 };
		{ GREY..INDENT.."Ancient Treasure (Lower)", OBJECT, 141979 };
	};
	ZulGurub = {
		ZoneName = { "Zul'Gurub", 19 };
		Acronym = "ZG";
		Location = { "Stranglethorn Vale", 33 };
		LevelRange = "56-70";
		PlayerLimit = "20";
		Continent = "Eastern Kingdoms";
		{ ORNG.."Rep: Zandalar Tribe", FACTION, 270 };
		{ ORNG.."Key: Mudskunk Lure (Gahz'ranka)", ITEM, 19974 };
		{ ORNG.."Key: Gurubashi Mojo Madness (EoM)", ITEM, 19931 };
		{ BLUE.."A) Entrance" };
		{ GREY.."1) High Priestess Jeklik (Bat)", NPC, 14517 };
		{ GREY.."2) High Priest Venoxis (Snake)", NPC, 14507 };
		{ GREY.."3) Zanza the Restless", NPC, 15042 };
		{ GREY.."4) High Priestess Mar'li (Spider)", NPC, 14510 };
		{ GREY.."5) Bloodlord Mandokir (Raptor, Optional)", NPC, 11382 };
		{ GREY..INDENT.."Ohgan", NPC, 14988 };
		{ GREY.."6) Edge of Madness (Optional)" };
		{ GREY..INDENT.."Gri'lek (Random)", NPC, 15082 };
		{ GREY..INDENT.."Hazza'rah (Random)", NPC, 15083 };
		{ GREY..INDENT.."Renataki (Random)", NPC, 15084 };
		{ GREY..INDENT.."Wushoolay (Random)", NPC, 15085 };
		{ GREY.."7) Gahz'ranka (Optional, Summon)", NPC, 15114 };
		{ GREY.."8) High Priest Thekal (Tiger)", NPC, 14509 };
		{ GREY..INDENT.."Zealot Zath", NPC, 11348 };
		{ GREY..INDENT.."Zealot Lor'Khan", NPC, 11347 };
		{ GREY.."9) High Priestess Arlokk (Panther)", NPC, 14515 };
		{ GREY.."10) Jin'do the Hexxer (Undead, Optional)", NPC, 11380 };
		{ GREY.."11) Hakkar", NPC, 14834 };
		{ GREN.."1') Muddy Churning Waters" };
	};
	Naxxramas = {
		ZoneName = { "Naxxramas", 3456 };
		Acronym = "Nax";
		Location = { "Eastern Plaguelands", 139 };
		LevelRange = "60-70";
		PlayerLimit = "40";
		Continent = "Eastern Kingdoms";
		{ ORNG.."Attunement Required" };
		{ ORNG.."Rep: Argent Dawn", FACTION, 529 };
		{ BLUE.."A) Entrance" };
		{ BLUE..INDENT.."Archmage Tarsis Kir-Moldir", NPC, 16381 };
		{ BLUE..INDENT.."Mr. Bigglesworth (Wanders)", NPC, 16998 };
		{ GREY.."Abomination Wing" };
		{ GREY..INDENT.."1) Patchwerk", NPC, 16028 };
		{ GREY..INDENT.."2) Grobbulus", NPC, 15931 };
		{ GREY..INDENT.."3) Gluth", NPC, 15932 };
		{ GREY..INDENT.."4) Thaddius", NPC, 15928 };
		{ ORNG.."Spider Wing" };
		{ ORNG..INDENT.."1) Anub'Rekhan", NPC, 15956 };
		{ ORNG..INDENT.."2) Grand Widow Faerlina", NPC, 15953 };
		{ ORNG..INDENT.."3) Maexxna", NPC, 15952 };
		{ _RED.."Deathknight Wing" };
		{ _RED..INDENT.."1) Instructor Razuvious", NPC, 16061 };
		{ _RED..INDENT.."2) Gothik the Harvester", NPC, 16060 };
		{ _RED..INDENT.."3) The Four Horsemen" };
		{ _RED..INDENT..INDENT.."Thane Korth'azz", NPC, 16064 };
		{ _RED..INDENT..INDENT.."Lady Blaumeux", NPC, 16065 };
		{ _RED..INDENT..INDENT.."Highlord Mograine <The Ashbringer>", NPC, 16062 };
		{ _RED..INDENT..INDENT.."Sir Zeliek", NPC, 16063 };
		{ _RED..INDENT..INDENT.."Four Horsemen Chest", OBJECT, 181366 };
		{ PURP.."Plague Wing" };
		{ PURP..INDENT.."1) Noth the Plaguebringer", NPC, 15954 };
		{ PURP..INDENT.."2) Heigan the Unclean", NPC, 15936 };
		{ PURP..INDENT.."3) Loatheb", NPC, 16011 };
		{ GREN.."Frostwyrm Lair" };
		{ GREN..INDENT.."1) Sapphiron", NPC, 15989 };
		{ GREN..INDENT.."2) Kel'Thuzad", NPC, 15990 };
	};
	KarazhanStart = {
		ZoneName = { "Karazhan [A] (Start)", 2562 };
		Acronym = "Kara";
		Location = { "Deadwind Pass", 41 };
		LevelRange = "70";
		PlayerLimit = "10";
		Continent = "Eastern Kingdoms";
		{ ORNG.."Rep: The Violet Eye", FACTION, 967 };
		{ ORNG.."Key: The Master's Key", ITEM, 24490 };
		{ ORNG.."Key: Blackened Urn (Nightbane)", ITEM, 24140 };
		{ BLUE.."A) Front Entrance" };
		{ BLUE.."B) Staircase to the Ballroom (Moroes)" };
		{ BLUE.."C) Stairs to Upper Stable" };
		{ BLUE.."D) Ramp to the Guest Chambers (Maiden)" };
		{ BLUE.."E) Stairs to Opera House Orchestra Level" };
		{ BLUE.."F) Ramp from Mezzanine to Balcony" };
		{ BLUE.."G) Back Entrance" };
		{ BLUE.."H) Connection to Master's Terrace (Nightbane)" };
		{ BLUE.."I) Path to the Broken Stairs" };
		{ GREY.."1) Hastings <The Caretaker>", NPC, 16169 };
		{ GREY.."2) Servant Quarters" };
		{ GREY..INDENT.."Hyakiss the Lurker (Rare, Random)", NPC, 16179 };
		{ GREY..INDENT.."Rokad the Ravager (Rare, Random)", NPC, 16181 };
		{ GREY..INDENT.."Shadikith the Glider (Rare, Random)", NPC, 16180 };
		{ GREY.."3) Berthold <The Doorman>", NPC, 16153 };
		{ GREY.."4) Calliard <The Nightman>", NPC, 16159 };
		{ GREY.."5) Attumen the Huntsman", NPC, 15550 };
		{ GREY..INDENT.."Midnight", NPC, 16151 };
		{ GREY.."6) Koren <The Blacksmith>", NPC, 16388 };
		{ GREY.."7) Moroes <Tower Steward>", NPC, 15687 };
		{ GREY..INDENT.."Baroness Dorothea Millstipe (Random, Shadow Priest)", NPC, 19875 };
		{ GREY..INDENT.."Lady Catriona Von'Indi (Random, Holy Priest)", NPC, 19872 };
		{ GREY..INDENT.."Lady Keira Berrybuck (Random, Holy Paladin)", NPC, 17007 };
		{ GREY..INDENT.."Baron Rafe Dreuger (Random, Retribution Paladin)", NPC, 19874 };
		{ GREY..INDENT.."Lord Robin Daris (Random, Arms Warrior)", NPC, 19876 };
		{ GREY..INDENT.."Lord Crispin Ference (Random, Protection Warrior)", NPC, 19873 };
		{ GREY.."8) Bennett <The Sergeant at Arms>", NPC, 16426 };
		{ GREY.."9) Ebonlocke <The Noble>", NPC, 16806 };
		{ GREY.."10) Keanna's Log", OBJECT, 182199 };
		{ GREY.."11) Maiden of Virtue", NPC, 16457 };
		{ GREY.."12) Sebastian <The Organist>", NPC, 16811 };
		{ GREY.."13) Barnes <The Stage Manager>", NPC, 16812 };
		{ GREY.."14) The Opera Event" };
		{ GREY..INDENT.."Red Riding Hood (Random)" };
		{ GREY..INDENT..INDENT.."The Big Bad Wolf", NPC, 17521 };
		{ GREY..INDENT.."Wizard of Oz (Random)" };
		{ GREY..INDENT..INDENT.."Dorothee", NPC, 17535 };
		{ GREY..INDENT..INDENT.."Tito", NPC, 17548 };
		{ GREY..INDENT..INDENT.."Strawman", NPC, 17543 };
		{ GREY..INDENT..INDENT.."Tinhead", NPC, 17547 };
		{ GREY..INDENT..INDENT.."Roar", NPC, 17546 };
		{ GREY..INDENT..INDENT.."The Crone", NPC, 18168 };
		{ GREY..INDENT.."Romulo and Julianne (Random)" };
		{ GREY..INDENT..INDENT.."Romulo", NPC, 17533 };
		{ GREY..INDENT..INDENT.."Julianne", NPC, 17534 };
		{ GREY.."15) The Master's Terrace" };
		{ GREY..INDENT.."Nightbane (Summon)", NPC, 17225 };
	};
	KarazhanEnd = {
		ZoneName = { "Karazhan [B] (End)", 2562 };
		Acronym = "Kara";
		Location = { "Deadwind Pass", 41 };
		LevelRange = "70";
		PlayerLimit = "10";
		Continent = "Eastern Kingdoms";
		{ ORNG.."Rep: The Violet Eye", FACTION, 967 };
		{ ORNG.."Key: The Master's Key", ITEM, 24490 };
		{ BLUE.."I) Path to the Broken Stairs" };
		{ BLUE.."J) Broken Stairs" };
		{ BLUE.."K) Ramp to Guardian's Library (Shade of Aran)" };
		{ BLUE.."L) Suspicious Bookshelf (Passage to Illhoof)" };
		{ BLUE.."M) Ramp up to the Celestial Watch (Netherspite)" };
		{ BLUE..INDENT.."Ramp down to the Gamesman's Hall (Chess Event)" };
		{ BLUE.."N) Ramp to Medivh's Chamber" };
		{ BLUE.."O) Spiral Stairs to Netherspace (Prince)" };
		{ GREY.."16) The Curator", NPC, 15691 };
		{ GREY.."17) Wravien <The Mage>", NPC, 16813 };
		{ GREY.."18) Gradav <The Warlock>", NPC, 16814 };
		{ GREY.."19) Kamsis <The Conjurer>", NPC, 16815 };
		{ GREY.."20) Terestian Illhoof", NPC, 15688 };
		{ GREY..INDENT.."Kil'rek (Imp)", NPC, 17229 };
		{ GREY.."21) Shade of Aran", NPC, 16524 };
		{ GREY.."22) Netherspite", NPC, 15689 };
		{ GREY.."23) Ythyar (Repair and Rewards)", NPC, 17518 };
		{ GREY.."24) Echo of Medivh", NPC, 16816 };
		{ GREY.."25) Dust Covered Chest (Chess Event)", OBJECT, 185119 };
		{ GREY.."26) Prince Malchezaar", NPC, 15690 };
	};
	ZulAman = {
		ZoneName = { "Zul'Aman", 3805 };
		Acronym = "ZA";
		Location = { "Ghostlands", 3433 };
		LevelRange = "70";
		PlayerLimit = "10";
		Continent = "Eastern Kingdoms";
		{ BLUE.."A) Entrance" };
		{ BLUE..INDENT.."Harrison Jones", NPC, 24358 };
		{ GREY.."1) Nalorakk <Bear Avatar>", NPC, 23576 };
		{ GREY..INDENT.."Tanzar", NPC, 23790 };
		{ GREY..INDENT.."The Map of Zul'Aman", OBJECT, 186733 };
		{ GREY.."2) Akil'Zon <Eagle Avatar>", NPC, 23574 };
		{ GREY..INDENT.."Harkor", NPC, 23999 };
		{ GREY.."3) Jan'Alai <Dragonhawk Avatar>", NPC, 23578 };
		{ GREY..INDENT.."Kraz", NPC, 24024 };
		{ GREY.."4) Halazzi <Lynx Avatar>", NPC, 23577 };
		{ GREY..INDENT.."Ashli", NPC, 24001 };
		{ GREY.."5) Zungam", NPC, 23897 };
		{ GREY.."6) Hex Lord Malacrass", NPC, 24239 };
		{ GREY..INDENT.."Thurg (Random)", NPC, 24241 };
		{ GREY..INDENT.."Gazakroth (Random)", NPC, 24244 };
		{ GREY..INDENT.."Lord Raadan (Random)", NPC, 24243 };
		{ GREY..INDENT.."Darkheart (Random)", NPC, 24246 };
		{ GREY..INDENT.."Alyson Antille (Random)", NPC, 24240 };
		{ GREY..INDENT.."Slither (Random)", NPC, 24242 };
		{ GREY..INDENT.."Fenstalker (Random)", NPC, 24245 };
		{ GREY..INDENT.."Koragg (Random)", NPC, 24247 };
		{ GREY.."7) Zul'jin", NPC, 23863 };
		{ GREN.."1') Forest Frogs", NPC, 24396 };
		{ GREN..INDENT.."Kyren <Reagents>", NPC, 24409 };
		{ GREN..INDENT.."Gunter <Food Vendor>", NPC, 24408 };
		{ GREN..INDENT.."Adarrah", NPC, 24405 };
		{ GREN..INDENT.."Brennan", NPC, 24453 };
		{ GREN..INDENT.."Darwen", NPC, 24407 };
		{ GREN..INDENT.."Deez", NPC, 24403 };
		{ GREN..INDENT.."Galathryn", NPC, 24404 };
		{ GREN..INDENT.."Mitzi", NPC, 24445 };
		{ GREN..INDENT.."Mannuth", NPC, 24397 };
	};
	MagistersTerrace = {
		ZoneName = { "Magisters' Terrace", 4095 };
		Acronym = "MT";
		Location = { "Isle of Quel'Danas", 4080 };
		LevelRange = "70";
		PlayerLimit = "5";
		Continent = "Eastern Kingdoms";
		{ ORNG.."Rep: Shattered Sun Offensive", FACTION, 1077 };
		{ BLUE.."A) Entrance" };
		{ GREY.."1) Selin Fireheart", NPC, 24723 };
		{ GREY..INDENT.."Fel Crystals", NPC, 24722 };
		{ GREY.."2) Tyrith", NPC, 24822 };
		{ GREY.."3) Vexallus", NPC, 24744 };
		{ GREY.."4) Scrying Orb" };
		{ GREY..INDENT.."Kalecgos", NPC, 24850 };
		{ GREY.."5) Priestess Delrissa (Lower)", NPC, 24560 };
		{ GREY.."6) Kael'thas Sunstrider <Lord of the Blood Elves>", NPC, 24664 };
	};
	SunwellPlateau = {
		ZoneName = { "Sunwell Plateau", 4075 };
		Acronym = "SP";
		Location = { "Isle of Quel'Danas", 4080 };
		LevelRange = "70";
		PlayerLimit = "25";
		Continent = "Eastern Kingdoms";
		{ BLUE.."A) Entrance" };
		{ GREY.."1) Kalecgos", NPC, 24850 };
		{ GREY..INDENT.."Sathrovarr the Corruptor", NPC, 24892 };
		{ GREY.."2) Madrigosa", NPC, 24895 };
		{ GREY..INDENT.."Brutallus", NPC, 24882 };
		{ GREY..INDENT.."Felmyst", NPC, 25038 };
		{ GREY.."3) Eredar Twins (Lower)" };
		{ GREY..INDENT.."Grand Warlock Alythess (Lower)", NPC, 25166 };
		{ GREY..INDENT.."Lady Sacrolash (Lower)", NPC, 25165 };
		{ GREY..INDENT.."M'uru (Upper)", NPC, 25741 };
		{ GREY..INDENT.."Entropius (Upper)", NPC, 25840 };
		{ GREY.."4) Kil'jaeden" };
	};

--************************************************
-- Outland Instances
--************************************************
	
	HCBloodFurnace = {
		ZoneName = { "HFC: The Blood Furnace", 3713 };
		Location = { "Hellfire Citadel, Hellfire Peninsula", 3483 };
		Acronym = "BF";
		LevelRange = "60-68";
		PlayerLimit = "5";
		Continent = "Outland";
		{ ORNG.."Rep: Thrallmar (Horde)", FACTION, 947 };
		{ ORNG.."Rep: Honor Hold (Alliance)", FACTION, 946 };
		{ ORNG.."Key: Flamewrought Key (Heroic)", ITEM, 30637 };
		{ BLUE.."A) Entrance" };
		{ GREY.."1) The Maker", NPC, 17381 };
		{ GREY.."2) Broggok", NPC, 17380 };
		{ GREY.."3) Keli'dan the Breaker", NPC, 17377 };
	};
	HCTheShatteredHalls = {
		ZoneName = { "HFC: The Shattered Halls", 3714 };
		Location = { "Hellfire Citadel, Hellfire Peninsula", 3483 };
		Acronym = "SH";
		LevelRange = "69-70";
		PlayerLimit = "5";
		Continent = "Outland";
		{ ORNG.."Rep: Thrallmar (Horde)", FACTION, 947 };
		{ ORNG.."Rep: Honor Hold (Alliance)", FACTION, 946 };
		{ ORNG.."Key: Shattered Halls Key", ITEM, 28395 };
		{ ORNG.."Key: Flamewrought Key (Heroic)", ITEM, 30637 };
		{ BLUE.."A) Entrance" };
		{ GREY.."1) Randy Whizzlesprocket (Alliance, Heroic)", NPC, 17288 };
		{ GREY..INDENT.."Drisella (Horde, Heroic)", NPC, 17294 };
		{ GREY.."2) Grand Warlock Nethekurse", NPC, 16807 };
		{ GREY.."3) Blood Guard Porung (Heroic)", NPC, 20923 };
		{ GREY.."4) Warbringer O'mrogg", NPC, 16809 };
		{ GREY.."5) Warchief Kargath Bladefist", NPC, 16808 };
		{ GREY..INDENT.."Shattered Hand Executioner (Heroic)", NPC, 17301 };
		{ GREY..INDENT.."Private Jacint (Alliance, Heroic)", NPC, 17292 };
		{ GREY..INDENT.."Rifleman Brownbeard (Alliance, Heroic)", NPC, 17289 };
		{ GREY..INDENT.."Captain Alina (Alliance, Heroic)", NPC, 17290 };
		{ GREY..INDENT.."Scout Orgarr (Horde, Heroic)", NPC, 17297 };
		{ GREY..INDENT.."Korag Proudmane (Horde, Heroic)", NPC, 17295 };
		{ GREY..INDENT.."Captain Boneshatter (Horde, Heroic)", NPC, 17296 };
	};
	HCHellfireRamparts = {
		ZoneName = { "HFC: Hellfire Ramparts", 3562 };
		Location = { "Hellfire Citadel, Hellfire Peninsula", 3483 };
		Acronym = "Ramp";
		LevelRange = "59-67";
		PlayerLimit = "5";
		Continent = "Outland";
		{ ORNG.."Rep: Thrallmar (Horde)", FACTION, 947 };
		{ ORNG.."Rep: Honor Hold (Alliance)", FACTION, 946 };
		{ ORNG.."Key: Flamewrought Key (Heroic)", ITEM, 30637 };
		{ BLUE.."A) Entrance" };
		{ GREY.."1) Watchkeeper Gargolmar", NPC, 17306 };
		{ GREY.."2) Omor the Unscarred", NPC, 17308 };
		{ GREY.."3) Vazruden", NPC, 17537 };
		{ GREY..INDENT.."Nazan <Vazruden's Mount>", NPC, 17536 };
		{ GREY..INDENT.."Reinforced Fel Iron Chest", OBJECT, 185168 };
	};
	HCMagtheridonsLair = {
		ZoneName = { "HFC: Magtheridon's Lair", 3836 };
		Location = { "Hellfire Citadel, Hellfire Peninsula", 3483 };
		Acronym = "Mag";
		LevelRange = "70";
		PlayerLimit = "25";
		Continent = "Outland";
		{ ORNG.."Rep: Thrallmar (Horde)", FACTION, 947 };
		{ ORNG.."Rep: Honor Hold (Alliance)", FACTION, 946 };
		{ BLUE.."A) Entrance" };
		{ GREY.."1) Magtheridon", NPC, 17257 };
	};
	CFRTheSlavePens = {
		ZoneName = { "CR: The Slave Pens", 3717 };
		Location = { "Coilfang Reservoir, Zangarmarsh", 3521 };
		Acronym = "SP";
		LevelRange = "61-69";
		PlayerLimit = "5";
		Continent = "Outland";
		{ ORNG.."Rep: Cenarion Expedition", FACTION, 942 };
		{ ORNG.."Key: Reservoir Key (Heroic)", ITEM, 30623 };
		{ BLUE.."A) Entrance" };
		{ GREY.."1) Mennu the Betrayer", NPC, 17941 };
		{ GREY.."2) Weeder Greenthumb", NPC, 17890 };
		{ GREY.."3) Skar'this the Heretic (Heroic)", NPC, 22421 };
		{ GREY.."4) Rokmar the Crackler", NPC, 17991 };
		{ GREY.."5) Naturalist Bite", NPC, 17893 };
		{ GREY.."6) Quagmirran", NPC, 17942 };
	};
	CFRTheUnderbog = {
		ZoneName = { "CR: The Underbog", 3716 };
		Location = { "Coilfang Reservoir, Zangarmarsh", 3521 };
		Acronym = "Underbog";
		LevelRange = "62-70";
		PlayerLimit = "5";
		Continent = "Outland";
		{ ORNG.."Rep: Cenarion Expedition", FACTION, 942 };
		{ ORNG.."Key: Reservoir Key (Heroic)", ITEM, 30623 };
		{ BLUE.."A) Entrance" };
		{ GREY.."1) Hungarfen", NPC, 17770 };
		{ GREY..INDENT.."The Underspore", OBJECT, 182054 };
		{ GREY.."2) Ghaz'an", NPC, 18105 };
		{ GREY.."3) Earthbinder Rayge", NPC, 17885 };
		{ GREY.."4) Swamplord Musel'ek", NPC, 17826 };
		{ GREY..INDENT.."Claw <Swamplord Musel'ek's Pet>", NPC, 17827 };
		{ GREY.."5) The Black Stalker", NPC, 17882 };
	};
	CFRTheSteamvault = {
		ZoneName = { "CR: The Steamvault", 3715 };
		Location = { "Coilfang Reservoir, Zangarmarsh", 3521 };
		Acronym = "SV";
		LevelRange = "69-70";
		PlayerLimit = "5";
		Continent = "Outland";
		{ ORNG.."Rep: Cenarion Expedition", FACTION, 942 };
		{ ORNG.."Key: Reservoir Key (Heroic)", ITEM, 30623 };
		{ BLUE.."A) Entrance" };
		{ GREY.."1) Hydromancer Thespia", NPC, 17797 };
		{ GREY..INDENT.."Main Chambers Access Panel" };
		{ GREY.."2) Arcane Container", OBJECT, 182196 };
		{ GREY..INDENT.."Second Fragment Guardian", NPC, 22891 };
		{ GREY.."3) Mekgineer Steamrigger", NPC, 17796 };
		{ GREY..INDENT.."Main Chambers Access Panel" };
		{ GREY.."4) Warlord Kalithresh", NPC, 17798 };
	};
	CFRSerpentshrineCavern = {
		ZoneName = { "CR: Serpentshrine Cavern", 3607 };
		Location = { "Coilfang Reservoir, Zangarmarsh", 3521 };
		Acronym = "SC";
		LevelRange = "70";
		PlayerLimit = "25";
		Continent = "Outland";
		{ ORNG.."Rep: Cenarion Expedition", FACTION, 942 };
		{ BLUE.."A) Entrance" };
		{ GREY.."1) Hydross the Unstable <Duke of Currents>", NPC, 21216 };
		{ GREY.."2) The Lurker Below", NPC, 21217 };
		{ GREY.."3) Leotheras the Blind", NPC, 21215 };
		{ GREY.."4) Fathom-Lord Karathress", NPC, 21214 };
		{ GREY..INDENT.."Seer Olum", NPC, 22820 };
		{ GREY.."5) Morogrim Tidewalker", NPC, 21213 };
		{ GREY.."6) Lady Vashj <Coilfang Matron>", NPC, 21212 };
	};
	AuchManaTombs = {
		ZoneName = { "Auch: Mana-Tombs", 3792 };
		Location = { "Auchindoun, Terokkar Forest", 3519 };
		Acronym = "MT";
		LevelRange = "63-70";
		PlayerLimit = "5";
		Continent = "Outland";
		{ ORNG.."Rep: The Consortium", FACTION, 933 };
		{ ORNG.."Key: Auchenai Key (Heroic)", ITEM, 30633 };
		{ ORNG.."Key: The Eye of Haramad (Exalted, Yor)", ITEM, 32092 };
		{ BLUE.."A) Entrance" };
		{ GREY.."1) Pandemonius", NPC, 18341 };
		{ GREY..INDENT.."Shadow Lord Xiraxis", NPC, 19666 };
		{ GREY.."2) Ambassador Pax'ivi (Heroic)", NPC, 22928 };
		{ GREY.."3) Tavarok", NPC, 18343 };
		{ GREY.."4) Cryo-Engineer Sha'heen", NPC, 19671 };
		{ GREY..INDENT.."Ethereal Transporter Control Panel", OBJECT, 183877 };
		{ GREY.."5) Nexus-Prince Shaffar", NPC, 18344 };
		{ GREY..INDENT.."Yor <Void Hound of Shaffar> (Summon, Heroic)", NPC, 22930 };
	};
	AuchAuchenaiCrypts = {
		ZoneName = { "Auch: Auchenai Crypts", 3790 };
		Location = { "Auchindoun, Terokkar Forest", 3519 };
		Acronym = "AC";
		LevelRange = "64-70";
		PlayerLimit = "5";
		Continent = "Outland";
		{ ORNG.."Rep: Lower City", FACTION, 1011 };
		{ ORNG.."Key: Auchenai Key (Heroic)", ITEM, 30633 };
		{ BLUE.."A) Entrance" };
		{ GREY.."1) Shirrak the Dead Watcher", NPC, 18371 };
		{ GREY.."2) Exarch Maladaar", NPC, 18373 };
		{ GREY..INDENT.."Avatar of the Martyred", NPC, 18478 };
		{ GREY..INDENT.."D'ore", NPC, 19412 };
	};
	AuchSethekkHalls = {
		ZoneName = { "Auch: Sethekk Halls", 3791 };
		Location = { "Auchindoun, Terokkar Forest", 3519 };
		Acronym = "Sethekk";
		LevelRange = "66-70";
		PlayerLimit = "5";
		Continent = "Outland";
		{ ORNG.."Rep: Lower City", FACTION, 1011 };
		{ ORNG.."Key: Auchenai Key (Heroic)", ITEM, 30633 };
		{ ORNG.."Key: Essence-Infused Moonstone (Anzu)", ITEM, 32449 };
		{ BLUE.."A) Entrance" };
		{ GREY.."1) Darkweaver Syth", NPC, 18472 };
		{ GREY..INDENT.."Lakka", NPC, 18956 };
		{ GREY.."2) The Saga of Terokk", OBJECT, 183050 };
		{ GREY..INDENT.."Anzu (Summon, Heroic)", NPC, 23035 };
		{ GREY.."3) Talon King Ikiss", NPC, 18473 };
	};
	AuchShadowLabyrinth = {
		ZoneName = { "Auch: Shadow Labyrinth", 3789 };
		Location = { "Auchindoun, Terokkar Forest", 3519 };
		Acronym = "SL";
		LevelRange = "69-70";
		PlayerLimit = "5";
		Continent = "Outland";
		{ ORNG.."Rep: Lower City", FACTION, 1011 };
		{ ORNG.."Key: Shadow Labyrinth Key", ITEM, 27991 };
		{ ORNG.."Key: Auchenai Key (Heroic)", ITEM, 30633 };
		{ BLUE.."A) Entrance" };
		{ GREY.."1) Spy To'gun", NPC, 18891 };
		{ GREY.."2) Ambassador Hellmaw", NPC, 18731 };
		{ GREY.."3) Blackheart the Inciter", NPC, 18667 };
		{ GREY.."4) Grandmaster Vorpil", NPC, 18732 };
		{ GREY..INDENT.."The Codex of Blood", OBJECT, 182947 };
		{ GREY.."5) Murmur", NPC, 18708 };
		{ GREY.."6) Arcane Container", OBJECT, 182196 };
		{ GREY..INDENT.."First Fragment Guardian", NPC, 22890 };
	};
	TempestKeepBotanica = {
		ZoneName = { "TK: The Botanica", 3847 };
		Location = { "Tempest Keep, Netherstorm", 3523 };
		Acronym = "Bota";
		LevelRange = "69-70";
		PlayerLimit = "5";
		Continent = "Outland";
		{ ORNG.."Rep: The Sha'tar", FACTION, 935 };
		{ ORNG.."Key: Warpforged Key (Heroic)", ITEM, 30634 };
		{ BLUE.."A) Entrance" };
		{ GREY.."1) Commander Sarannis", NPC, 17976 };
		{ GREY.."2) High Botanist Freywinn", NPC, 17975 };
		{ GREY.."3) Thorngrin the Tender", NPC, 17978 };
		{ GREY.."4) Laj", NPC, 17980 };
		{ GREY.."5) Warp Splinter", NPC, 17977 };
	};
	TempestKeepArcatraz = {
		ZoneName = { "TK: The Arcatraz", 3846 };
		Location = { "Tempest Keep, Netherstorm", 3523 };
		Acronym = "Arca";
		LevelRange = "69-70";
		PlayerLimit = "5";
		Continent = "Outland";
		{ ORNG.."Rep: The Sha'tar", FACTION, 935 };
		{ ORNG.."Key: Key to the Arcatraz", ITEM, 31084 };
		{ ORNG.."Key: Warpforged Key (Heroic)", ITEM, 30634 };
		{ BLUE.."A) Entrance" };
		{ GREY.."1) Zereketh the Unbound", NPC, 20870 };
		{ GREY.."2) Arcane Container", OBJECT, 182196 };
		{ GREY..INDENT.."Third Fragment Guardian", NPC, 22892 };
		{ GREY.."3) Dalliah the Doomsayer", NPC, 20885 };
		{ GREY.."4) Wrath-Scryer Soccothrates", NPC, 20886 };
		{ GREY.."5) Udalo", NPC, 21962 };
		{ GREY.."6) Harbinger Skyriss", NPC, 20912 };
		{ GREY..INDENT.."Warden Mellichar", NPC, 20904 };
		{ GREY..INDENT.."Millhouse Manastorm", NPC, 20977 };
	};
	TempestKeepMechanar = {
		ZoneName = { "TK: The Mechanar", 3849 };
		Location = { "Tempest Keep, Netherstorm", 3523 };
		Acronym = "Mech";
		LevelRange = "68-70";
		PlayerLimit = "5";
		Continent = "Outland";
		{ ORNG.."Rep: The Sha'tar", FACTION, 935 };
		{ ORNG.."Key: Warpforged Key (Heroic)", ITEM, 30634 };
		{ BLUE.."A) Entrance" };
		{ GREY.."1) Gatewatcher Gyro-Kill", NPC, 19218 };
		{ GREY.."2) Gatewatcher Iron-Hand", NPC, 19710 };
		{ GREY..INDENT.."Cache of the Legion", OBJECT, 184465 };
		{ GREY.."3) Mechano-Lord Capacitus", NPC, 19219 };
		{ GREY..INDENT.."Overcharged Manacell", OBJECT, 185015 };
		{ GREY.."4) Nethermancer Sepethrea", NPC, 19221 };
		{ GREY.."5) Pathaleon the Calculator", NPC, 19220 };
	};
	TempestKeepTheEye = {
		ZoneName = { "TK: The Eye", 3842 };
		Location = { "Tempest Keep, Netherstorm", 3523 };
		Acronym = "Eye";
		LevelRange = "70";
		PlayerLimit = "25";
		Continent = "Outland";
		{ ORNG.."Rep: The Sha'tar", FACTION, 935 };
		{ ORNG.."Key: The Tempest Key", ITEM, 31704 };
		{ BLUE.."A) Entrance" };
		{ GREY.."1) Al'ar <Phoenix God>", NPC, 19514 };
		{ GREY.."2) Void Reaver", NPC, 19516 };
		{ GREY.."3) High Astromancer Solarian", NPC, 18805 };
		{ GREY.."4) Kael'Thas Sunstrider <Lord of the Blood Elves>", NPC, 19622 };
		{ GREY..INDENT.."Thaladred the Darkener <Advisor to Kael'thas> (Warrior)", NPC, 20064 };
		{ GREY..INDENT.."Master Engineer Telonicus <Advisor to Kael'thas> (Hunter)", NPC, 20063 };
		{ GREY..INDENT.."Grand Astromancer Capernian <Advisor to Kael'thas> (Mage)", NPC, 20062 };
		{ GREY..INDENT.."Lord Sanguinar <The Blood Hammer> (Paladin)", NPC, 20060 };
	};
	GruulsLair = {
		ZoneName = { "Gruul's Lair", 3618 };
		Location = { "Blade's Edge Mountains", 3522 };
		Acronym = "GL";
		LevelRange = "70";
		PlayerLimit = "25";
		Continent = "Outland";
		{ BLUE.."A) Entrance" };
		{ GREY.."1) High King Maulgar <Lord of the Ogres>", NPC, 18831 };
		{ GREY..INDENT.."Kiggler the Crazed (Shaman)", NPC, 18835 };
		{ GREY..INDENT.."Blindeye the Seer (Priest)", NPC, 18836 };
		{ GREY..INDENT.."Olm the Summoner (Warlock)", NPC, 18834 };
		{ GREY..INDENT.."Krosh Firehand (Mage)", NPC, 18832 };
		{ GREY.."2) Gruul the Dragonkiller", NPC, 19044 };
	};
	BlackTempleStart = {
		ZoneName = { "Black Temple [A] (Start)", 3959 };
		Location = { "Shadowmoon Valley", 3520 };
		Acronym = "BT";
		LevelRange = "70";
		PlayerLimit = "25";
		Continent = "Outland";
		{ ORNG.."Rep: Ashtongue Deathsworn", FACTION, 1012 };
		{ ORNG.."Key: Medallion of Karabor", ITEM, 32649 };
		{ BLUE.."A) Entrance" };
		{ BLUE.."B) Towards Reliquary of Souls" };
		{ BLUE.."C) Towards Teron Gorefiend" };
		{ BLUE.."D) Towards Illidan Stormrage" };
		{ GREY.."1) Spirit of Olum", NPC, 23411 };
		{ GREY.."2) High Warlord Naj'entus", NPC, 22887 };
		{ GREY.."3) Supremus", NPC, 22898 };
		{ GREY.."4) Shade of Akama", NPC, 22841 };
		{ GREY.."5) Spirit of Udalo", NPC, 23410 };
		{ GREY..INDENT.."Aluyen <Reagents>", NPC, 23157 };
		{ GREY..INDENT.."Okuno <Ashtongue Deathsworn Quartermaster>", NPC, 23159 };
		{ GREY..INDENT.."Seer Kanai", NPC, 23158 };
	};
	BlackTempleBasement = {
		ZoneName = { "Black Temple [B] (Basement)", 3959 };
		Location = { "Shadowmoon Valley", 3520 };
		Acronym = "BT";
		LevelRange = "70";
		PlayerLimit = "25";
		Continent = "Outland";
		{ ORNG.."Rep: Ashtongue Deathsworn", FACTION, 1012 };
		{ ORNG.."Key: Medallion of Karabor", ITEM, 32649 };
		{ BLUE.."B) Entrance" };
		{ BLUE.."C) Entrance" };
		{ GREY.."6) Gurtogg Bloodboil", NPC, 22948 };
		{ GREY.."7) Reliquary of Souls" };
		{ GREY..INDENT.."Essence of Suffering", NPC, 23418 };
		{ GREY..INDENT.."Essence of Desire", NPC, 23419 };
		{ GREY..INDENT.."Essence of Anger", NPC, 23420 };
		{ GREY.."8) Teron Gorefiend", NPC, 22871 };
	};
	BlackTempleTop = {
		ZoneName = { "Black Temple [C] (Top)", 3959 };
		Location = { "Shadowmoon Valley", 3520 };
		Acronym = "BT";
		LevelRange = "70";
		PlayerLimit = "25";
		Continent = "Outland";
		{ ORNG.."Rep: Ashtongue Deathsworn", FACTION, 1012 };
		{ ORNG.."Key: Medallion of Karabor", ITEM, 32649 };
		{ BLUE.."D) Entrance" };
		{ GREY.."9) Mother Shahraz", NPC, 22947 };
		{ GREY.."10) The Illidari Council", NPC, 23426 };
		{ GREY..INDENT.."Lady Malande (Priest)", NPC, 22951 };
		{ GREY..INDENT.."Gathios the Shatterer (Paladin)", NPC, 22949 };
		{ GREY..INDENT.."High Nethermancer Zerevor (Mage)", NPC, 22950 };
		{ GREY..INDENT.."Veras Darkshadow (Rogue)", NPC, 22952 };
		{ GREY.."11) Illidan Stormrage <The Betrayer>", NPC, 22917 };
	};
	--]]
};
