--[[

	Atlas, a World of Warcraft instance map browser
	Copyright 2005-2010 Dan Gilbert <dan.b.gilbert@gmail.com>
	Copyright 2010 Lothaer <lothayer@gmail.com >, Atlas Team

	This file is part of Atlas.

	Atlas is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2 of the License, or
	(at your option) any later version.

	Atlas is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with Atlas; if not, write to the Free Software
	Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

--]]

local BF = Atlas_GetLocaleLibBabble("LibBabble-Faction-3.0");
local BZ = Atlas_GetLocaleLibBabble("LibBabble-SubZone-3.0");
local AL = LibStub("AceLocale-3.0"):GetLocale("Atlas_Transportation");

local BLUE = "|cff6666ff";
local GREN = "|cff66cc33";
local _RED = "|cffcc3333";
local ORNG = "|cffcc9933";
local PURP = "|cff9900ff";
local WHIT = "|cffffffff";
local CYAN = "|cff00ffff";
local GREY = "|cff999999";
local INDENT = "      ";

local ZONE = 1;
local NPC = 2;
local ITEM = 3;
local OBJECT = 4;
local FACTION = 5;
local QUEST = 6;

local myCategory = AL["Transportation Maps"];

local myData = {
	TransAllianceEast = {
		ZoneName = { BZ["Eastern Kingdoms"].." ("..BF["Alliance"]..")" };
		{ _RED..BZ["Docks"] };
		{ ORNG.." A') "..BZ["Valgarde"]..", "..BZ["Howling Fjord"]..", "..BZ["Northrend"] };
		{ ORNG.." B') "..BZ["Valiance Keep"]..", "..BZ["Borean Tundra"]..", "..BZ["Northrend"] };
		{ ORNG.." C') "..BZ["Rut'theran Village"]..", "..BZ["Teldrassil"]..", "..BZ["Kalimdor"] };
		{ ORNG.." D') "..BZ["Ratchet"]..", "..BZ["Northern Barrens"]..", "..BZ["Kalimdor"] };
		{ ORNG.." E') "..BZ["Theramore"]..", "..BZ["Dustwallow Marsh"]..", "..BZ["Kalimdor"] };
		{ "" };
		{ _RED..AL["Portals"] };
		{ PURP.." A) "..BZ["The Dark Portal"]..", "..BZ["Blasted Lands"] };
		{ PURP.." B) "..BZ["Baradin Base Camp"]..", "..BZ["Tol Barad Peninsula"] };
		{ PURP.." A') "..BZ["The Stair of Destiny"]..", "..BZ["Hellfire Peninsula"]..", "..BZ["Outland"] };
		{ PURP.." B') "..BZ["Deepholm"]..", "..BZ["The Maelstrom"] };
		{ "" };
		{ _RED..AL["Taxi Nodes"] };
		{ BLUE..BZ["Isle of Quel'Danas"] };
		{ WHIT.." 1) "..BZ["Shattered Sun Staging Area"] };
		{ "" };
		{ BLUE..BZ["Ghostlands"] };
		{ WHIT.." 2) "..BZ["Zul'Aman"] };
		{ "" };
		{ BLUE..BZ["Eastern Plaguelands"] };
		{ GREN.." 3) "..BZ["Acherus: The Ebon Hold"].." ("..AL["Death Knight Only"]..")" };
		{ WHIT.." 4) "..BZ["Light's Hope Chapel"] };
		{ WHIT.." 5) "..BZ["Eastwall Tower"] };
		{ WHIT.." 6) "..BZ["Northpass Tower"] };
		{ WHIT.." 7) "..BZ["Plaguewood Tower"] };
		{ WHIT.." 8) "..BZ["Light's Shield Tower"] };
		{ WHIT.." 9) "..BZ["Crown Guard Tower"] };
		{ WHIT.."10) "..BZ["Thondroril River"] };
		{ "" };
		{ BLUE..BZ["Western Plaguelands"] };
		{ WHIT.."11) "..BZ["Hearthglen"] };
		{ WHIT.."12) "..BZ["The Menders' Stead"] };
		{ WHIT.."13) "..BZ["Andorhal"] };
		{ WHIT.."14) "..BZ["Chillwind Camp"] };
		{ "" };
		{ BLUE..BZ["The Hinterlands"] };
		{ WHIT.."15) "..BZ["Aerie Peak"] };
		{ WHIT.."16) "..BZ["Stormfeather Outpost"] };
		{ "" };
		{ BLUE..BZ["Arathi Highlands"] };
		{ WHIT.."17) "..BZ["Refuge Pointe"] };
		{ "" };
		{ BLUE..BZ["Wetlands"] };
		{ WHIT.."18) "..BZ["Dun Modr"] };
		{ WHIT.."19) "..BZ["Whelgar's Retreat"] };
		{ WHIT.."20) "..BZ["Greenwarden's Grove"] };
		{ WHIT.."21) "..BZ["Menethil Harbor"] };
		{ WHIT.."22) "..BZ["Slabchisel's Survey"] };
		{ "" };
		{ BLUE..BZ["Twilight Highlands"] };
		{ WHIT.."23) "..BZ["Vermillion Redoubt"] };
		{ WHIT.."24) "..BZ["Thundermar"] };
		{ WHIT.."25) "..BZ["Kirthaven"] };
		{ WHIT.."26) "..BZ["Victor's Point"] };
		{ WHIT.."27) "..BZ["Firebeard's Patrol"] };
		{ WHIT.."28) "..BZ["Highbank"] };
		{ "" };
		{ BLUE..BZ["Dun Morogh"] };
		{ WHIT.."29) "..BZ["Ironforge"] };
		{ WHIT.."30) "..BZ["Kharanos"] };
		{ WHIT.."31) "..BZ["Gol'Bolar Quarry"] };
		{ "" };
		{ BLUE..BZ["Loch Modan"] };
		{ WHIT.."32) "..BZ["Thelsamar"] };
		{ WHIT.."33) "..BZ["Farstrider Lodge"] };
		{ "" };
		{ BLUE..BZ["Searing Gorge"] };
		{ WHIT.."34) "..BZ["Thorium Point"] };
		{ WHIT.."35) "..BZ["Iron Summit"] };
		{ "" };
		{ BLUE..BZ["Badlands"] };
		{ WHIT.."36) "..BZ["Dragon's Mouth"] };
		{ WHIT.."37) "..BZ["Dustwind Dig"] };
		{ WHIT.."38) "..BZ["Fuselight"] };
		{ "" };
		{ BLUE..BZ["Burning Steppes"] };
		{ WHIT.."39) "..BZ["Chiselgrip"] };
		{ WHIT.."40) "..BZ["Morgan's Vigil"] };
		{ "" };
		{ BLUE..BZ["Elwynn Forest"] };
		{ WHIT.."41) "..BZ["Stormwind"] };
		{ WHIT.."42) "..BZ["Goldshire"] };
		{ WHIT.."43) "..BZ["Eastvale Logging Camp"] };
		{ "" };
		{ BLUE..BZ["Redridge Mountains"] };
		{ WHIT.."44) "..BZ["Lakeshire"] };
		{ WHIT.."45) "..BZ["Camp Everstill"] };
		{ WHIT.."46) "..BZ["Shalewind Canyon"] };
		{ "" };
		{ BLUE..BZ["Westfall"] };
		{ WHIT.."47) "..BZ["Furlbrow's Pumpkin Farm"] };
		{ WHIT.."48) "..BZ["Moonbrook"] };
		{ WHIT.."49) "..BZ["Sentinel Hill"] };
		{ "" };
		{ BLUE..BZ["Duskwood"] };
		{ WHIT.."50) "..BZ["Raven Hill"] };
		{ WHIT.."51) "..BZ["Darkshire"] };
		{ "" };
		{ BLUE..BZ["Swamp of Sorrows"] };
		{ WHIT.."52) "..BZ["The Harborage"] };
		{ WHIT.."53) "..BZ["Marshtide Watch"] };
		{ WHIT.."54) "..BZ["Bogpaddle"] };
		{ "" };
		{ BLUE..BZ["Northern Stranglethorn"] };
		{ WHIT.."55) "..BZ["Rebel Camp"] };
		{ WHIT.."56) "..BZ["Fort Livingston"] };
		{ "" };
		{ BLUE..BZ["The Cape of Stranglethorn"] };
		{ WHIT.."57) "..BZ["Explorers' League Digsite"] };
		{ WHIT.."58) "..BZ["Booty Bay"] };
		{ "" };
		{ BLUE..BZ["Blasted Lands"] };
		{ WHIT.."59) "..BZ["Nethergarde Keep"] };
		{ WHIT.."60) "..BZ["Surwich"] };
		{ "" };
		{ BLUE..BZ["Vashj'ir"] };
		{ WHIT.."61) "..BZ["Sandy Beach"] };
		{ CYAN.."62) "..BZ["Smuggler's Scar"].." ("..AL["Seahorse"]..")" };
		{ CYAN.."63) "..BZ["Sandy Beach"].." ("..AL["Seahorse"]..")" };
		{ CYAN.."64) "..BZ["Silver Tide Hollow"].." ("..AL["Seahorse"]..")" };
		{ CYAN.."65) "..BZ["Tranquil Wash"].." ("..AL["Seahorse"]..")" };
		{ CYAN.."66) "..BZ["Darkbreak Cove"].." ("..AL["Seahorse"]..")" };
		{ "" };
		{ _RED..AL["Legend"] };
		{ PURP.."-- : "..AL["Portal / Waygate Path to the destination"] };
		{ CYAN.."-- : "..AL["Ship / Zeppelin sailing path to destination"] };
		{ GREN.."-- : "..BZ["Deeprun Tram"] };
	};
	TransAllianceWest = {
		ZoneName = { BZ["Kalimdor"].." ("..BF["Alliance"]..")" };
		{ _RED..BZ["Docks"] };
		{ ORNG.." A') "..BZ["Stormwind Harbor"]..", "..BZ["Elwynn Forest"]..", "..BZ["Eastern Kingdoms"] };
		{ ORNG.." B') "..BZ["Menethil Harbor"]..", "..BZ["Wetlands"]..", "..BZ["Eastern Kingdoms"] };
		{ ORNG.." C') "..BZ["Booty Bay"]..", "..BZ["The Cape of Stranglethorn"]..", "..BZ["Eastern Kingdoms"] };
		{ "" };
		{ _RED..AL["Portals"].." / "..BZ["Waygate"] };
		{ PURP.." A) "..BZ["Shaper's Terrace"]..", "..BZ["Un'Goro Crater"] };
		{ PURP.." A') "..BZ["The Dark Portal"]..", "..BZ["Blasted Lands"]..", "..BZ["Eastern Kingdoms"] };
		{ PURP.." B') "..BZ["Waygate"]..", "..BZ["Sholazar Basin"]..", "..BZ["Northrend"] };
		{ "" };
		{ _RED..AL["Taxi Nodes"] };
		{ BLUE..BZ["Teldrassil"] };
		{ WHIT.." 1) "..BZ["Dolanaar"] };
		{ WHIT.." 2) "..BZ["Darnassus"] };
		{ WHIT.." 3) "..BZ["Rut'theran Village"] };
		{ "" };
		{ BLUE..BZ["Azuremyst Isle"].." / "..BZ["Bloodmyst Isle"] };
		{ WHIT.." 4) "..BZ["Azure Watch"] };
		{ WHIT.." 5) "..BZ["The Exodar"] };
		{ WHIT.." 6) "..BZ["Blood Watch"] };
		{ "" };
		{ BLUE..BZ["Darkshore"] };
		{ WHIT.." 7) "..BZ["Lor'danel"] };
		{ WHIT.." 8) "..BZ["Grove of the Ancients"] };
		{ "" };
		{ BLUE..BZ["Ashenvale"] };
		{ WHIT.." 9) "..BZ["Blackfathom Camp"] };
		{ WHIT.."10) "..BZ["Astranaar"] };
		{ WHIT.."11) "..BZ["Forest Song"] };
		{ WHIT.."12) "..BZ["Stardust Spire"] };
		{ "" };
		{ BLUE..BZ["Stonetalon Mountains"] };
		{ WHIT.."13) "..BZ["Windshear Fortress"] };
		{ WHIT.."14) "..BZ["Mirkfallon Post"] };
		{ WHIT.."15) "..BZ["Thal'darah Overlook"] };
		{ WHIT.."16) "..BZ["Farwatcher's Glen"] };
		{ WHIT.."17) "..BZ["Northwatch Expedition Base Camp"] };
		{ "" };
		{ BLUE..BZ["Desolace"] };
		{ WHIT.."18) "..BZ["Nijel's Point"] };
		{ WHIT.."19) "..BZ["Thunk's Abode"] };
		{ WHIT.."20) "..BZ["Karnum's Glade"] };
		{ WHIT.."21) "..BZ["Ethel Rethor"] };
		{ WHIT.."22) "..BZ["Thargad's Camp"] };
		{ "" };
		{ BLUE..BZ["Feralas"] };
		{ WHIT.."23) "..BZ["Dreamer's Rest"] };
		{ WHIT.."24) "..BZ["Feathermoon"] };
		{ WHIT.."25) "..BZ["Ruins of Feathermoon"] };
		{ WHIT.."26) "..BZ["Tower of Estulan"] };
		{ WHIT.."27) "..BZ["Shadebough"] };
		{ "" };
		{ BLUE..BZ["Northern Barrens"].." / "..BZ["Southern Barrens"] };
		{ WHIT.."28) "..BZ["Ratchet"] };
		{ WHIT.."29) "..BZ["Northwatch Hold"] };
		{ WHIT.."30) "..BZ["Honor's Stand"] };
		{ WHIT.."31) "..BZ["Fort Triumph"] };
		{ "" };
		{ BLUE..BZ["Dustwallow Marsh"] };
		{ WHIT.."32) "..BZ["Theramore"] };
		{ WHIT.."33) "..BZ["Mudsprocket"] };
		{ "" };
		{ BLUE..BZ["Thousand Needles"] };
		{ WHIT.."34) "..BZ["Fizzle & Pozzik's Speedbarge"] };
		{ "" };
		{ BLUE..BZ["Tanaris"] };
		{ WHIT.."35) "..BZ["Gadgetzan"] };
		{ WHIT.."36) "..BZ["Gunstan's Dig"] };
		{ WHIT.."37) "..BZ["Bootlegger Outpost"] };
		{ "" };
		{ BLUE..BZ["Un'Goro Crater"] };
		{ WHIT.."38) "..BZ["Marshal's Stand"] };
		{ WHIT.."39) "..BZ["Mossy Pile"] };
		{ "" };
		{ BLUE..BZ["Silithus"] };
		{ WHIT.."40) "..BZ["Cenarion Hold"] };
		{ "" };
		{ BLUE..BZ["Felwood"] };
		{ WHIT.."41) "..BZ["Emerald Sanctuary"] };
		{ WHIT.."42) "..BZ["Wildheart Point"] };
		{ WHIT.."43) "..BZ["Whisperwind Grove"] };
		{ WHIT.."44) "..BZ["Talonbranch Glade"] };
		{ "" };
		{ BLUE..BZ["Moonglade"] };
		{ GREN.."45) "..BZ["Nighthaven"].." ("..AL["Druid-only"]..")" };
		{ WHIT.."46) "..BZ["Moonglade"] };
		{ WHIT..INDENT.."("..AL["South of the path along Lake Elune'ara"]..")" };
		{ "" };
		{ BLUE..BZ["Winterspring"] };
		{ WHIT.."47) "..BZ["Everlook"] };
		{ "" };
		{ BLUE..BZ["Mount Hyjal"] };
		{ WHIT.."48) "..BZ["Nordrassil"] };
		{ WHIT.."49) "..BZ["Shrine of Aviana"] };
		{ WHIT.."50) "..BZ["Shrine of Aessina"] };
		{ WHIT.."51) "..BZ["Gates of Sothann"] };
		{ "" };
		{ BLUE..BZ["Uldum"] };
		{ WHIT.."52) "..BZ["Ramkahen"] };
		{ WHIT.."53) "..BZ["Oasis of Vir'sar"] };
		{ WHIT.."54) "..BZ["Schnottz's Landing"] };
		{ "" };
		{ _RED..AL["Legend"] };
		{ PURP.."-- : "..AL["Portal / Waygate Path to the destination"] };
		{ CYAN.."-- : "..AL["Ship / Zeppelin sailing path to destination"] };	
	};
	TransHordeEast = {
		ZoneName = { BZ["Eastern Kingdoms"].." ("..BF["Horde"]..")" };
		{ _RED..AL["Zeppelin Towers"].." / "..BZ["Docks"] };
		{ ORNG.." A') "..BZ["Vengeance Landing"]..", "..BZ["Howling Fjord"]..", "..BZ["Northrend"] };
		{ ORNG.." B') "..BZ["Orgrimmar"]..", "..BZ["Durotar"]..", "..BZ["Kalimdor"] };
		{ ORNG.." C') "..BZ["Ratchet"]..", "..BZ["Northern Barrens"]..", "..BZ["Kalimdor"] };
		{ "" };
		{ _RED..AL["Portals"].." / "..AL["Orb of Translocation"] };
		{ PURP.." A) "..BZ["The Dark Portal"]..", "..BZ["Blasted Lands"] };
		{ PURP.." B) "..BZ["Hellscream's Grasp"]..", "..BZ["Tol Barad Peninsula"] };
		{ PURP.." A') "..BZ["The Stair of Destiny"]..", "..BZ["Hellfire Peninsula"]..", "..BZ["Outland"] };
		{ PURP.." B') "..BZ["Orgrimmar"]..", "..BZ["Durotar"]..", "..BZ["Kalimdor"] };
		{ "" };
		{ _RED..AL["Taxi Nodes"] };
		{ BLUE..BZ["Isle of Quel'Danas"] };
		{ WHIT.." 1) "..BZ["Shattered Sun Staging Area"] };
		{ "" };
		{ BLUE..BZ["Eversong Woods"] };
		{ WHIT.." 2) "..BZ["Falconwing Square"] };
		{ WHIT.." 3) "..BZ["Silvermoon City"] };
		{ WHIT.." 4) "..BZ["Fairbreeze Village"] };
		{ "" };
		{ BLUE..BZ["Ghostlands"] };
		{ WHIT.." 5) "..BZ["Tranquillien"] };
		{ WHIT.." 6) "..BZ["Zul'Aman"] };
		{ "" };
		{ BLUE..BZ["Eastern Plaguelands"] };
		{ GREN.." 7) "..BZ["Acherus: The Ebon Hold"].." ("..AL["Death Knight Only"]..")" };
		{ WHIT.." 8) "..BZ["Light's Hope Chapel"] };
		{ WHIT.." 9) "..BZ["Northpass Tower"] };
		{ WHIT.."10) "..BZ["Plaguewood Tower"] };
		{ WHIT.."11) "..BZ["Eastwall Tower"] };
		{ WHIT.."12) "..BZ["Light's Shield Tower"] };
		{ WHIT.."13) "..BZ["Crown Guard Tower"] };
		{ WHIT.."14) "..BZ["Thondroril River"] };
		{ "" };
		{ BLUE..BZ["Western Plaguelands"] };
		{ WHIT.."15) "..BZ["The Menders' Stead"] };
		{ WHIT.."16) "..BZ["Hearthglen"] };
		{ WHIT.."17) "..BZ["Andorhal"] };
		{ "" };
		{ BLUE..BZ["Tirisfal Glades"] };
		{ WHIT.."18) "..BZ["The Bulwark"] };
		{ WHIT.."19) "..BZ["Brill"] };
		{ WHIT.."20) "..BZ["Undercity"] };
		{ "" };
		{ BLUE..BZ["Silverpine Forest"] };
		{ WHIT.."21) "..BZ["Forsaken High Command"] };
		{ WHIT.."22) "..BZ["Forsaken Rear Guard"] };
		{ WHIT.."23) "..BZ["The Sepulcher"] };
		{ WHIT.."24) "..BZ["The Forsaken Front"] };
		{ "" };
		{ BLUE..BZ["Hillsbrad Foothills"] };
		{ WHIT.."25) "..BZ["Southpoint Gate"] };
		{ WHIT.."26) "..BZ["Ruins of Southshore"] };
		{ WHIT.."27) "..BZ["Tarren Mill"] };
		{ WHIT.."28) "..BZ["Eastpoint Tower"] };
		{ "" };
		{ BLUE..BZ["Arathi Highlands"] };
		{ WHIT.."29) "..BZ["Galen's Fall"] };
		{ WHIT.."30) "..BZ["Hammerfall"] };
		{ "" };
		{ BLUE..BZ["The Hinterlands"] };
		{ WHIT.."31) "..BZ["Hiri'watha Research Station"] };
		{ WHIT.."32) "..BZ["Revantusk Village"] };
		{ "" };
		{ BLUE..BZ["Twilight Highlands"] };
		{ WHIT.."33) "..BZ["Vermillion Redoubt"] };
		{ WHIT.."34) "..BZ["The Gullet"] };
		{ WHIT.."35) "..BZ["Bloodgulch"] };
		{ WHIT.."36) "..BZ["The Krazzworks"] };
		{ WHIT.."37) "..BZ["Dragonmaw Port"] };
		{ WHIT.."38) "..BZ["Crushblow"] };
		{ "" };
		{ BLUE..BZ["Badlands"] };
		{ WHIT.."39) "..BZ["Fuselight"] };
		{ WHIT.."40) "..BZ["Bloodwatcher Point"] };
		{ WHIT.."41) "..BZ["New Kargath"] };
		{ "" };
		{ BLUE..BZ["Searing Gorge"] };
		{ WHIT.."42) "..BZ["Thorium Point"] };
		{ WHIT.."43) "..BZ["Iron Summit"] };
		{ "" };
		{ BLUE..BZ["Burning Steppes"] };
		{ WHIT.."44) "..BZ["Flame Crest"] };
		{ WHIT.."45) "..BZ["Chiselgrip"] };
		{ WHIT.."46) "..BZ["Flamestar Post"] };
		{ "" };
		{ BLUE..BZ["Swamp of Sorrows"] };
		{ WHIT.."47) "..BZ["Bogpaddle"] };
		{ WHIT.."48) "..BZ["Stonard"] };
		{ "" };
		{ BLUE..BZ["Blasted Lands"] };
		{ WHIT.."49) "..BZ["Dreadmaul Hold"] };
		{ WHIT.."50) "..BZ["Sunveil Excursion"] };
		{ "" };
		{ BLUE..BZ["Northern Stranglethorn"] };
		{ WHIT.."51) "..BZ["Bambala"] };
		{ WHIT.."52) "..BZ["Grom'gol Base Camp"] };
		{ "" };
		{ BLUE..BZ["The Cape of Stranglethorn"] };
		{ WHIT.."53) "..BZ["Hardwrench Hideaway"] };
		{ WHIT.."54) "..BZ["Booty Bay"] };
		{ "" };
		{ BLUE..BZ["Vashj'ir"] };
		{ WHIT.."55) "..BZ["Sandy Beach"] };
		{ CYAN.."56) "..BZ["Smuggler's Scar"].." ("..AL["Seahorse"]..")" };
		{ CYAN.."57) "..BZ["Sandy Beach"].." ("..AL["Seahorse"]..")" };
		{ CYAN.."58) "..BZ["Silver Tide Hollow"].." ("..AL["Seahorse"]..")" };
		{ CYAN.."59) "..BZ["Legion's Rest"].." ("..AL["Seahorse"]..")" };
		{ CYAN.."60) "..BZ["Tenebrous Cavern"].." ("..AL["Seahorse"]..")" };
		{ "" };
		{ _RED..AL["Legend"] };
		{ PURP.."-- : "..AL["Portal / Waygate Path to the destination"] };
		{ CYAN.."-- : "..AL["Ship / Zeppelin sailing path to destination"] };
	};
	TransHordeWest = {
		ZoneName = { BZ["Kalimdor"].." ("..BF["Horde"]..")" };
		{ _RED..AL["Zeppelin Towers"].." / "..BZ["Docks"] };
		{ ORNG.." A') "..BZ["Warsong Hold"]..", "..BZ["Borean Tundra"]..", "..BZ["Northrend"] };
		{ ORNG.." B') "..BZ["Undercity"]..", "..BZ["Tirisfal Glades"]..", "..BZ["Eastern Kingdoms"] };
		{ ORNG.." C') "..BZ["Grom'gol Base Camp"]..", "..BZ["Northern Stranglethorn"]..", "..BZ["Eastern Kingdoms"] };
		{ ORNG.." D') "..BZ["Booty Bay"]..", "..BZ["The Cape of Stranglethorn"]..", "..BZ["Eastern Kingdoms"] };
		{ "" };
		{ _RED..AL["Portals"].." / "..BZ["Waygate"] };
		{ PURP.." A) "..BZ["Shaper's Terrace"]..", "..BZ["Un'Goro Crater"] };
		{ PURP.." A') "..BZ["Waygate"]..", "..BZ["Sholazar Basin"]..", "..BZ["Northrend"] };
		{ PURP.." B') "..BZ["Deepholm"]..", "..BZ["The Maelstrom"] };
		{ PURP.." C') "..BZ["Hellscream's Grasp"]..", "..BZ["Tol Barad Peninsula"]..", "..BZ["Eastern Kingdoms"] };
		{ PURP.." D') "..BZ["Vashj'ir"]..", "..BZ["Eastern Kingdoms"] };
		{ PURP.." E') "..BZ["The Dark Portal"]..", "..BZ["Blasted Lands"]..", "..BZ["Eastern Kingdoms"] };
		{ "" };
		{ _RED..AL["Taxi Nodes"] };
		{ BLUE..BZ["Mulgore"] };
		{ WHIT.." 1) "..BZ["Bloodhoof Village"] };
		{ WHIT.." 2) "..BZ["Thunder Bluff"] };
		{ "" };
		{ BLUE..BZ["Durotar"] };
		{ WHIT.." 3) "..BZ["Sen'jin Village"] };
		{ WHIT.." 4) "..BZ["Razor Hill"] };
		{ WHIT.." 5) "..BZ["Orgrimmar"] };
		{ "" };
		{ BLUE..BZ["Azshara"] };
		{ WHIT.." 6) "..BZ["Valormok"] };
		{ WHIT.." 7) "..BZ["Southern Rocketway"] };
		{ WHIT.." 8) "..BZ["Bilgewater Harbor"] };
		{ WHIT.." 9) "..BZ["Northern Rocketway"] };
		{ "" };
		{ BLUE..BZ["Northern Barrens"] };
		{ WHIT.."10) "..BZ["Nozzlepot's Outpost"] };
		{ WHIT.."11) "..BZ["Crossroads"] };
		{ WHIT.."12) "..BZ["Ratchet"] };
		{ "" };
		{ BLUE..BZ["Ashenvale"] };
		{ WHIT.."13) "..BZ["The Mor'Shan Ramparts"] };
		{ WHIT.."14) "..BZ["Splintertree Post"] };
		{ WHIT.."15) "..BZ["Silverwind Refuge"] };
		{ WHIT.."16) "..BZ["Hellscream's Watch"] };
		{ WHIT.."17) "..BZ["Zoram'gar Outpost"] };
		{ "" };
		{ BLUE..BZ["Stonetalon Mountains"] };
		{ WHIT.."18) "..BZ["Cliffwalker Post"] };
		{ WHIT.."19) "..BZ["The Sludgewerks"] };
		{ WHIT.."20) "..BZ["Sun Rock Retreat"] };
		{ WHIT.."21) "..BZ["Krom'gar Fortress"] };
		{ WHIT.."22) "..BZ["Malaka'jin"] };
		{ "" };
		{ BLUE..BZ["Desolace"] };
		{ WHIT.."23) "..BZ["Thunk's Abode"] };
		{ WHIT.."24) "..BZ["Karnum's Glade"] };
		{ WHIT.."25) "..BZ["Furien's Post"] };
		{ WHIT.."26) "..BZ["Ethel Rethor"] };
		{ WHIT.."27) "..BZ["Shadowprey Village"] };
		{ "" };
		{ BLUE..BZ["Southern Barrens"] };
		{ WHIT.."28) "..BZ["Hunter's Hill"] };
		{ WHIT.."29) "..BZ["Desolation Hold"] };
		{ "" };
		{ BLUE..BZ["Dustwallow Marsh"] };
		{ WHIT.."30) "..BZ["Brackenwall Village"] };
		{ WHIT.."31) "..BZ["Mudsprocket"] };
		{ "" };
		{ BLUE..BZ["Feralas"] };
		{ WHIT.."32) "..BZ["Camp Ataya"] };
		{ WHIT.."33) "..BZ["Stonemaul Hold"] };
		{ WHIT.."34) "..BZ["Camp Mojache"] };
		{ "" };
		{ BLUE..BZ["Thousand Needles"] };
		{ WHIT.."35) "..BZ["Westreach Summit"] };
		{ WHIT.."36) "..BZ["Fizzle & Pozzik's Speedbarge"] };
		{ "" };
		{ BLUE..BZ["Tanaris"] };
		{ WHIT.."37) "..BZ["Gadgetzan"] };
		{ WHIT.."38) "..BZ["Bootlegger Outpost"] };
		{ WHIT.."39) "..BZ["Dawnrise Expedition"] };
		{ "" };
		{ BLUE..BZ["Un'Goro Crater"] };
		{ WHIT.."40) "..BZ["Marshal's Stand"] };
		{ WHIT.."41) "..BZ["Mossy Pile"] };
		{ "" };
		{ BLUE..BZ["Silithus"] };
		{ WHIT.."42) "..BZ["Cenarion Hold"] };
		{ "" };
		{ BLUE..BZ["Felwood"] };
		{ WHIT.."43) "..BZ["Emerald Sanctuary"] };
		{ WHIT.."44) "..BZ["Wildheart Point"] };
		{ WHIT.."45) "..BZ["Whisperwind Grove"] };
		{ WHIT.."46) "..BZ["Irontree Clearing"] };
		{ "" };
		{ BLUE..BZ["Moonglade"] };
		{ WHIT.."47) "..BZ["Moonglade"] };
		{ WHIT..INDENT.."("..AL["West of the path to Timbermaw Hold"]..")" };
		{ GREN.."48) "..BZ["Nighthaven"].." ("..AL["Druid-only"]..")" };
		{ "" };
		{ BLUE..BZ["Winterspring"] };
		{ WHIT.."49) "..BZ["Everlook"] };
		{ "" };
		{ BLUE..BZ["Mount Hyjal"] };
		{ WHIT.."50) "..BZ["Nordrassil"] };
		{ WHIT.."51) "..BZ["Shrine of Aviana"] };
		{ WHIT.."52) "..BZ["Shrine of Aessina"] };
		{ WHIT.."53) "..BZ["Gates of Sothann"] };
		{ "" };
		{ BLUE..BZ["Uldum"] };
		{ WHIT.."54) "..BZ["Ramkahen"] };
		{ WHIT.."55) "..BZ["Oasis of Vir'sar"] };
		{ WHIT.."56) "..BZ["Schnottz's Landing"] };
		{ "" };
		{ _RED..AL["Legend"] };
		{ PURP.."-- : "..AL["Portal / Waygate Path to the destination"] };
		{ CYAN.."-- : "..AL["Ship / Zeppelin sailing path to destination"] };	
	};
	TransAllianceOutland = {
		ZoneName = { BZ["Outland"].." ("..BF["Alliance"]..")" };
		{ BLUE.."A) "..BZ["The Dark Portal"]..", ".._RED..BZ["Blasted Lands"], ZONE, 4 };
		{ BLUE.."B) "..BZ["Stormwind City"]..", ".._RED..BZ["Elwynn Forest"], ZONE, 12 };
		{ BLUE.."C) "..BZ["Sun's Reach Sanctum"]..", ".._RED..BZ["Isle of Quel'Danas"], ZONE, 4080 };
		{ BLUE..INDENT..BZ["Caverns of Time"]..", ".._RED..BZ["Tanaris"], ZONE, 440 };
		{ WHIT.."1) "..BZ["The Dark Portal"]..", ".._RED..BZ["Hellfire Peninsula"], ZONE, 3483 };
		{ WHIT.."2) "..BZ["Shatter Point"]..", ".._RED..BZ["Hellfire Peninsula"], ZONE, 3483 };
		{ WHIT.."3) "..BZ["Honor Hold"]..", ".._RED..BZ["Hellfire Peninsula"], ZONE, 3483 };
		{ WHIT.."4) "..BZ["Temple of Telhamat"]..", ".._RED..BZ["Hellfire Peninsula"], ZONE, 3483 };
		{ WHIT.."5) "..BZ["Telredor"]..", ".._RED..BZ["Zangarmarsh"], ZONE, 3521 };
		{ WHIT.."6) "..BZ["Orebor Harborage"]..", ".._RED..BZ["Zangarmarsh"], ZONE, 3521 };
		{ WHIT.."7) "..BZ["Telaar"]..", ".._RED..BZ["Nagrand"], ZONE, 3518 };
		{ WHIT.."8) "..BZ["Shattrath City"]..", ".._RED..BZ["Terokkar Forest"], ZONE, 3519 };
		{ WHIT.."9) "..BZ["Allerian Stronghold"]..", ".._RED..BZ["Terokkar Forest"], ZONE, 3519 };
		{ WHIT.."10) "..BZ["Wildhammer Stronghold"]..", ".._RED..BZ["Shadowmoon Valley"], ZONE, 3520 };
		{ WHIT.."11) "..BZ["Altar of Sha'tar"]..", ".._RED..BZ["Shadowmoon Valley"]..BLUE.." ("..BF["The Aldor"]..")", ZONE, 3520 , FACTION, 932 };
		{ WHIT.."12) "..BZ["Sanctum of the Stars"]..", ".._RED..BZ["Shadowmoon Valley"]..BLUE.." ("..BF["The Scryers"]..")", ZONE, 3520 , FACTION, 934 };
		{ WHIT.."13) "..BZ["Sylvanaar"]..", ".._RED..BZ["Blade's Edge Mountains"], ZONE, 3522 };
		{ WHIT.."14) "..BZ["Evergrove"]..", ".._RED..BZ["Blade's Edge Mountains"], ZONE, 3522 };
		{ WHIT.."15) "..BZ["Toshley's Station"]..", ".._RED..BZ["Blade's Edge Mountains"], ZONE, 3522 };
		{ WHIT.."16) "..BZ["Area 52"]..", ".._RED..BZ["Netherstorm"], ZONE, 3523 };
		{ WHIT.."17) "..BZ["The Stormspire"]..", ".._RED..BZ["Netherstorm"], ZONE, 3523 };
		{ WHIT.."18) "..BZ["Cosmowrench"]..", ".._RED..BZ["Netherstorm"], ZONE, 3523 };
		{ GREN.."1') "..BZ["Blackwind Landing"]..", ".._RED..BZ["Terokkar Forest"], ZONE, 3519 };
		{ GREN.."2') "..BZ["Skyguard Outpost"]..", ".._RED..BZ["Blade's Edge Mountains"], ZONE, 3522 };
		{ GREN..INDENT.."("..AL["Requires honored faction with Sha'tari Skyguard"]..")", FACTION, 1031 };
	};
	TransHordeOutland = {
		ZoneName = { BZ["Outland"].." ("..BF["Horde"]..")" };
		{ BLUE.."A) "..BZ["The Dark Portal"]..", ".._RED..BZ["Blasted Lands"], ZONE, 4 };
		{ BLUE.."B) "..BZ["Orgrimmar"]..", ".._RED..BZ["Durotar"], ZONE, 14 };
		{ BLUE.."C) "..BZ["Sun's Reach Sanctum"]..", ".._RED..BZ["Isle of Quel'Danas"], ZONE, 4080 };
		{ BLUE..INDENT..BZ["Caverns of Time"]..", ".._RED..BZ["Tanaris"], ZONE, 440 };
		{ WHIT.."1) "..BZ["The Dark Portal"]..", ".._RED..BZ["Hellfire Peninsula"], ZONE, 3483 };
		{ WHIT.."2) "..BZ["Thrallmar"]..", ".._RED..BZ["Hellfire Peninsula"], ZONE, 3483 };
		{ WHIT.."3) "..BZ["Spinebreaker Post"]..", ".._RED..BZ["Hellfire Peninsula"], ZONE, 3483 };
		{ WHIT.."4) "..BZ["Falcon Watch"]..", ".._RED..BZ["Hellfire Peninsula"], ZONE, 3483 };
		{ WHIT.."5) "..BZ["Swamprat Post"]..", ".._RED..BZ["Zangarmarsh"], ZONE, 3521 };
		{ WHIT.."6) "..BZ["Zabra'jin"]..", ".._RED..BZ["Zangarmarsh"], ZONE, 3521 };
		{ WHIT.."7) "..BZ["Garadar"]..", ".._RED..BZ["Nagrand"], ZONE, 3518 };
		{ WHIT.."8) "..BZ["Shattrath City"]..", ".._RED..BZ["Terokkar Forest"], ZONE, 3519 };
		{ WHIT.."9) "..BZ["Stonebreaker Hold"]..", ".._RED..BZ["Terokkar Forest"], ZONE, 3519 };
		{ WHIT.."10) "..BZ["Shadowmoon Village"]..", ".._RED..BZ["Shadowmoon Valley"], ZONE, 3520 };
		{ WHIT.."11) "..BZ["Altar of Sha'tar"]..", ".._RED..BZ["Shadowmoon Valley"]..BLUE.." ("..BF["The Aldor"]..")", ZONE, 3520 , FACTION, 932 };
		{ WHIT.."12) "..BZ["Sanctum of the Stars"]..", ".._RED..BZ["Shadowmoon Valley"]..BLUE.." ("..BF["The Scryers"]..")", ZONE, 3520 , FACTION, 934 };
		{ WHIT.."13) "..BZ["Thunderlord Stronghold"]..", ".._RED..BZ["Blade's Edge Mountains"], ZONE, 3522 };
		{ WHIT.."14) "..BZ["Evergrove"]..", ".._RED..BZ["Blade's Edge Mountains"], ZONE, 3522 };
		{ WHIT.."15) "..BZ["Mok'Nathal Village"]..", ".._RED..BZ["Blade's Edge Mountains"], ZONE, 3522 };
		{ WHIT.."16) "..BZ["Area 52"]..", ".._RED..BZ["Netherstorm"], ZONE, 3523 };
		{ WHIT.."17) "..BZ["The Stormspire"]..", ".._RED..BZ["Netherstorm"], ZONE, 3523 };
		{ WHIT.."18) "..BZ["Cosmowrench"]..", ".._RED..BZ["Netherstorm"], ZONE, 3523 };
		{ GREN.."1') "..BZ["Blackwind Landing"]..", ".._RED..BZ["Terokkar Forest"], ZONE, 3519 };
		{ GREN.."2') "..BZ["Skyguard Outpost"]..", ".._RED..BZ["Blade's Edge Mountains"], ZONE, 3522 };
		{ GREN..INDENT.."("..AL["Requires honored faction with Sha'tari Skyguard"]..")", FACTION, 1031 };
	};
	TransAllianceNorthrend = {
		ZoneName = { BZ["Northrend"].." ("..BF["Alliance"]..")" };
		{ _RED..BZ["Docks"] };
		{ BLUE.." A') "..BZ["Stormwind City"]..", "..BZ["Elwynn Forest"], ZONE, 12 };
		{ BLUE.." B') "..BZ["Menethil Harbor"]..", "..BZ["Wetlands"], ZONE, 11 };
		{ "" };
		{ _RED..AL["Portals"].." / "..BZ["Waygate"] };
		{ BLUE.." ?) "..BZ["Caverns of Time"]..", "..BZ["Tanaris"], ZONE, 440 };
		{ "" };
		{ _RED..AL["Taxi Nodes"] };
		{ WHIT.."1) "..BZ["Valiance Keep"]..", ".._RED..BZ["Borean Tundra"], ZONE, 3537 };
		{ WHIT.."2) "..BZ["Amber Ledge"]..", ".._RED..BZ["Borean Tundra"], ZONE, 3537 };
		{ WHIT.."3) "..BZ["Transitus Shield"]..", ".._RED..BZ["Coldarra"], ZONE, 3537 };
		{ WHIT.."4) "..BZ["Fizzcrank Airstrip"]..", ".._RED..BZ["Borean Tundra"], ZONE, 3537 };
		{ WHIT.."5) "..BZ["Unu'pe"]..", ".._RED..BZ["Borean Tundra"], ZONE, 3537 };
		{ WHIT.."6) "..BZ["Nesingwary Base Camp"]..", ".._RED..BZ["Sholazar Basin"], ZONE, 3711 };
		{ WHIT.."7) "..BZ["River's Heart"]..", ".._RED..BZ["Sholazar Basin"], ZONE, 3711 };
		{ WHIT.."8) "..BZ["Stars' Rest"]..", ".._RED..BZ["Dragonblight"], ZONE, 65 };
		{ WHIT.."9) "..BZ["Moa'ki Harbor"]..", ".._RED..BZ["Dragonblight"], ZONE, 65 };
		{ WHIT.."10) "..BZ["Fordragon Hold"]..", ".._RED..BZ["Dragonblight"], ZONE, 65 };
		{ WHIT.."11) "..BZ["Wyrmrest Temple"]..", ".._RED..BZ["Dragonblight"], ZONE, 65 };
		{ WHIT.."12) "..BZ["Wintergarde Keep"]..", ".._RED..BZ["Dragonblight"], ZONE, 65 };
		{ WHIT.."13) "..BZ["Westguard Keep"]..", ".._RED..BZ["Howling Fjord"], ZONE, 495 };
		{ WHIT.."14) "..BZ["Kamagua"]..", ".._RED..BZ["Howling Fjord"], ZONE, 495 };
		{ WHIT.."15) "..BZ["Valgarde"]..", ".._RED..BZ["Howling Fjord"], ZONE, 495 };
		{ WHIT.."16) "..BZ["Fort Wildervar"]..", ".._RED..BZ["Howling Fjord"], ZONE, 495 };
		{ WHIT.."17) "..BZ["Amberpine Lodge"]..", ".._RED..BZ["Grizzly Hills"], ZONE, 394 };
		{ WHIT.."18) "..BZ["Westfall Brigade Encampment"]..", ".._RED..BZ["Grizzly Hills"], ZONE, 394 };
		{ WHIT.."19) "..BZ["Gundrak"]..", ".._RED..BZ["Zul'Drak"], ZONE, 66 };
		{ WHIT.."20) "..BZ["Zim'Torga"]..", ".._RED..BZ["Zul'Drak"], ZONE, 66 };
		{ WHIT.."21) "..BZ["The Argent Stand"]..", ".._RED..BZ["Zul'Drak"], ZONE, 66 };
		{ WHIT.."22) "..BZ["Light's Breach"]..", ".._RED..BZ["Zul'Drak"], ZONE, 66 };
		{ WHIT.."23) "..BZ["Ebon Watch"]..", ".._RED..BZ["Zul'Drak"], ZONE, 66 };
		{ WHIT.."24) "..BZ["Windrunner's Overlook"]..", ".._RED..BZ["Crystalsong Forest"], ZONE, 2817 };
		{ WHIT.."25) "..BZ["Dalaran"]..", ".._RED..BZ["Crystalsong Forest"], ZONE, 2817 };
		{ WHIT.."26) "..BZ["Frosthold"]..", ".._RED..BZ["The Storm Peaks"], ZONE, 67 };
		{ WHIT.."27) "..BZ["K3"]..", ".._RED..BZ["The Storm Peaks"], ZONE, 67 };
		{ WHIT.."28) "..BZ["Bouldercrag's Refuge"]..", ".._RED..BZ["The Storm Peaks"], ZONE, 67 };
		{ WHIT.."29) "..BZ["Ulduar"]..", ".._RED..BZ["The Storm Peaks"], ZONE, 67 };
		{ WHIT.."30) "..BZ["Dun Niffelem"]..", ".._RED..BZ["The Storm Peaks"], ZONE, 67 };
		{ WHIT.."31) "..BZ["The Argent Vanguard"]..", ".._RED..BZ["Icecrown"], ZONE, 210 };
		{ WHIT.."32) "..BZ["Crusaders' Pinnacle"]..", ".._RED..BZ["Icecrown"], ZONE, 210 };
		{ WHIT.."33) "..BZ["Argent Tournament Grounds"]..", ".._RED..BZ["Icecrown"], ZONE, 210 };
		{ WHIT.."34) "..BZ["The Shadow Vault"]..", ".._RED..BZ["Icecrown"], ZONE, 210 };
		{ WHIT.."35) "..BZ["Death's Rise"]..", ".._RED..BZ["Icecrown"], ZONE, 210 };
		{ WHIT.."36) "..BZ["Valiance Landing Camp"]..", ".._RED..BZ["Wintergrasp"], ZONE, 4197 };
		{ "" };
		{ _RED..AL["Legend"] };
		{ PURP.."-- : "..AL["Portal / Waygate Path to the destination"] };
		{ CYAN.."-- : "..AL["Ship / Zeppelin sailing path to destination"] };	
	};
	TransHordeNorthrend = {
		ZoneName = { BZ["Northrend"].." ("..BF["Horde"]..")" };
		{ BLUE.."A) "..BZ["Orgrimmar"]..", ".._RED..BZ["Durotar"], ZONE, 14 };
		{ BLUE.."B) "..BZ["Undercity"]..", ".._RED..BZ["Tirisfal Glades"], ZONE, 85 };
		{ BLUE.."C) "..BZ["Caverns of Time"]..", ".._RED..BZ["Tanaris"], ZONE, 440 };
		{ WHIT.."1) "..BZ["Warsong Hold"]..", ".._RED..BZ["Borean Tundra"], ZONE, 3537 };
		{ WHIT.."2) "..BZ["Amber Ledge"]..", ".._RED..BZ["Borean Tundra"], ZONE, 3537 };
		{ WHIT.."3) "..BZ["Transitus Shield"]..", ".._RED..BZ["Coldarra"], ZONE, 3537 };
		{ WHIT.."4) "..BZ["Bor'gorok Outpost"]..", ".._RED..BZ["Borean Tundra"], ZONE, 3537 };
		{ WHIT.."5) "..BZ["Taunka'le Village"]..", ".._RED..BZ["Borean Tundra"], ZONE, 3537 };
		{ WHIT.."6) "..BZ["Unu'pe"]..", ".._RED..BZ["Borean Tundra"], ZONE, 3537 };
		{ WHIT.."7) "..BZ["Nesingwary Base Camp"]..", ".._RED..BZ["Sholazar Basin"], ZONE, 3711 };
		{ WHIT.."8) "..BZ["River's Heart"]..", ".._RED..BZ["Sholazar Basin"], ZONE, 3711 };
		{ WHIT.."9) "..BZ["Agmar's Hammer"]..", ".._RED..BZ["Dragonblight"], ZONE, 65 };
		{ WHIT.."10) "..BZ["Moa'ki Harbor"]..", ".._RED..BZ["Dragonblight"], ZONE, 65 };
		{ WHIT.."11) "..BZ["Kor'kron Vanguard"]..", ".._RED..BZ["Dragonblight"], ZONE, 65 };
		{ WHIT.."12) "..BZ["Wyrmrest Temple"]..", ".._RED..BZ["Dragonblight"], ZONE, 65 };
		{ WHIT.."13) "..BZ["Venomspite"]..", ".._RED..BZ["Dragonblight"], ZONE, 65 };
		{ WHIT.."14) "..BZ["Kamagua"]..", ".._RED..BZ["Howling Fjord"], ZONE, 495 };
		{ WHIT.."15) "..BZ["New Agamand"]..", ".._RED..BZ["Howling Fjord"], ZONE, 495 };
		{ WHIT.."16) "..BZ["Vengeance Landing"]..", ".._RED..BZ["Howling Fjord"], ZONE, 495 };
		{ WHIT.."17) "..BZ["Apothecary Camp"]..", ".._RED..BZ["Howling Fjord"], ZONE, 495 };
		{ WHIT.."18) "..BZ["Camp Winterhoof"]..", ".._RED..BZ["Howling Fjord"], ZONE, 495 };
		{ WHIT.."19) "..BZ["Conquest Hold"]..", ".._RED..BZ["Grizzly Hills"], ZONE, 394 };
		{ WHIT.."20) "..BZ["Camp Oneqwah"]..", ".._RED..BZ["Grizzly Hills"], ZONE, 394 };
		{ WHIT.."21) "..BZ["Gundrak"]..", ".._RED..BZ["Zul'Drak"], ZONE, 66 };
		{ WHIT.."22) "..BZ["Zim'Torga"]..", ".._RED..BZ["Zul'Drak"], ZONE, 66 };
		{ WHIT.."23) "..BZ["The Argent Stand"]..", ".._RED..BZ["Zul'Drak"], ZONE, 66 };
		{ WHIT.."24) "..BZ["Light's Breach"]..", ".._RED..BZ["Zul'Drak"], ZONE, 66 };
		{ WHIT.."25) "..BZ["Ebon Watch"]..", ".._RED..BZ["Zul'Drak"], ZONE, 66 };
		{ WHIT.."26) "..BZ["Sunreaver's Command"]..", ".._RED..BZ["Crystalsong Forest"], ZONE, 2817 };
		{ WHIT.."27) "..BZ["Dalaran"]..", ".._RED..BZ["Crystalsong Forest"], ZONE, 2817 };
		{ WHIT.."28) "..BZ["K3"]..", ".._RED..BZ["The Storm Peaks"], ZONE, 67 };
		{ WHIT.."29) "..BZ["Camp Tunka'lo"]..", ".._RED..BZ["The Storm Peaks"], ZONE, 67 };
		{ WHIT.."30) "..BZ["Grom'arsh Crash-Site"]..", ".._RED..BZ["The Storm Peaks"], ZONE, 67 };
		{ WHIT.."31) "..BZ["Bouldercrag's Refuge"]..", ".._RED..BZ["The Storm Peaks"], ZONE, 67 };
		{ WHIT.."32) "..BZ["Ulduar"]..", ".._RED..BZ["The Storm Peaks"], ZONE, 67 };
		{ WHIT.."33) "..BZ["Dun Niffelem"]..", ".._RED..BZ["The Storm Peaks"], ZONE, 67 };
		{ WHIT.."34) "..BZ["The Argent Vanguard"]..", ".._RED..BZ["Icecrown"], ZONE, 210 };
		{ WHIT.."35) "..BZ["Crusaders' Pinnacle"]..", ".._RED..BZ["Icecrown"], ZONE, 210 };
		{ WHIT.."36) "..BZ["Argent Tournament Grounds"]..", ".._RED..BZ["Icecrown"], ZONE, 210 };
		{ WHIT.."37) "..BZ["The Shadow Vault"]..", ".._RED..BZ["Icecrown"], ZONE, 210 };
		{ WHIT.."38) "..BZ["Death's Rise"]..", ".._RED..BZ["Icecrown"], ZONE, 210 };
		{ WHIT.."39) "..BZ["Warsong Camp"]..", ".._RED..BZ["Wintergrasp"], ZONE, 4197 };
	};
	TransMaelstrom = {
		ZoneName= { BZ["The Maelstrom"] };
		{ _RED..AL["Portals"] };
		{ PURP.." A) "..BZ["Temple of Earth"]..", "..BZ["Deepholm"] };
		{ PURP.." A') "..BZ["Stormwind City"]..", "..BZ["Elwynn Forest"]..", "..BZ["Eastern Kingdoms"] };
		{ PURP.." B') "..BZ["Orgrimmar"]..", "..BZ["Durotar"]..", "..BZ["Kalimdor"] };
		{ "" };
		{ _RED..AL["Legend"] };
		{ PURP.."-- : "..AL["Portal / Waygate Path to the destination"] };
		
	};
};

Atlas_RegisterPlugin("Atlas_Transportation", myCategory, myData);
